// Curated Russian (learned) -> Hungarian (native) starter vocabulary.
// Each entry: ru (word), hu (meaning), level (A1..C2), pos, ex (Russian example),
// exHu (Hungarian translation of the example). Examples are kept short and simple.
// Easy to extend: just add more objects. Exposed as window.RU_WORDS.

window.RU_WORDS = [
  // ── A1 ──────────────────────────────────────────────────────────────────
  { ru: 'привет', hu: 'szia', level: 'A1', pos: 'indulatszó', ex: 'Привет, как дела?', exHu: 'Szia, hogy vagy?' },
  { ru: 'пока', hu: 'szia (viszlát)', level: 'A1', pos: 'indulatszó', ex: 'Пока, до завтра!', exHu: 'Szia, holnapig!' },
  { ru: 'здравствуйте', hu: 'jó napot (üdvözlés)', level: 'A1', pos: 'indulatszó', ex: 'Здравствуйте, я Анна.', exHu: 'Jó napot, Anna vagyok.' },
  { ru: 'спасибо', hu: 'köszönöm', level: 'A1', pos: 'indulatszó', ex: 'Спасибо большое!', exHu: 'Nagyon köszönöm!' },
  { ru: 'пожалуйста', hu: 'kérlek / szívesen', level: 'A1', pos: 'indulatszó', ex: 'Кофе, пожалуйста.', exHu: 'Egy kávét kérek.' },
  { ru: 'извините', hu: 'elnézést', level: 'A1', pos: 'indulatszó', ex: 'Извините, где метро?', exHu: 'Elnézést, hol a metró?' },
  { ru: 'да', hu: 'igen', level: 'A1', pos: 'partikula', ex: 'Да, конечно.', exHu: 'Igen, persze.' },
  { ru: 'нет', hu: 'nem', level: 'A1', pos: 'partikula', ex: 'Нет, спасибо.', exHu: 'Nem, köszönöm.' },
  { ru: 'я', hu: 'én', level: 'A1', pos: 'névmás', ex: 'Я студент.', exHu: 'Diák vagyok.' },
  { ru: 'ты', hu: 'te', level: 'A1', pos: 'névmás', ex: 'Ты дома?', exHu: 'Otthon vagy?' },
  { ru: 'он', hu: 'ő (hímnem)', level: 'A1', pos: 'névmás', ex: 'Он мой брат.', exHu: 'Ő a bátyám.' },
  { ru: 'она', hu: 'ő (nőnem)', level: 'A1', pos: 'névmás', ex: 'Она врач.', exHu: 'Ő orvos.' },
  { ru: 'мы', hu: 'mi', level: 'A1', pos: 'névmás', ex: 'Мы друзья.', exHu: 'Barátok vagyunk.' },
  { ru: 'вы', hu: 'ti / ön', level: 'A1', pos: 'névmás', ex: 'Вы говорите по-русски?', exHu: 'Beszél oroszul?' },
  { ru: 'они', hu: 'ők', level: 'A1', pos: 'névmás', ex: 'Они здесь.', exHu: 'Itt vannak.' },
  { ru: 'это', hu: 'ez', level: 'A1', pos: 'névmás', ex: 'Это книга.', exHu: 'Ez egy könyv.' },
  { ru: 'кто', hu: 'ki', level: 'A1', pos: 'névmás', ex: 'Кто это?', exHu: 'Ki ez?' },
  { ru: 'что', hu: 'mi / mit', level: 'A1', pos: 'névmás', ex: 'Что это?', exHu: 'Ez mi?' },
  { ru: 'где', hu: 'hol', level: 'A1', pos: 'határozószó', ex: 'Где ты?', exHu: 'Hol vagy?' },
  { ru: 'когда', hu: 'mikor', level: 'A1', pos: 'határozószó', ex: 'Когда урок?', exHu: 'Mikor van az óra?' },
  { ru: 'как', hu: 'hogyan', level: 'A1', pos: 'határozószó', ex: 'Как тебя зовут?', exHu: 'Hogy hívnak?' },
  { ru: 'почему', hu: 'miért', level: 'A1', pos: 'határozószó', ex: 'Почему нет?', exHu: 'Miért nem?' },
  { ru: 'хорошо', hu: 'jól / rendben', level: 'A1', pos: 'határozószó', ex: 'Всё хорошо.', exHu: 'Minden rendben.' },
  { ru: 'плохо', hu: 'rosszul', level: 'A1', pos: 'határozószó', ex: 'Мне плохо.', exHu: 'Rosszul vagyok.' },
  { ru: 'день', hu: 'nap (napszak)', level: 'A1', pos: 'főnév', ex: 'Добрый день!', exHu: 'Jó napot!' },
  { ru: 'ночь', hu: 'éjszaka', level: 'A1', pos: 'főnév', ex: 'Спокойной ночи.', exHu: 'Jó éjszakát.' },
  { ru: 'утро', hu: 'reggel', level: 'A1', pos: 'főnév', ex: 'Доброе утро!', exHu: 'Jó reggelt!' },
  { ru: 'вечер', hu: 'este', level: 'A1', pos: 'főnév', ex: 'Добрый вечер!', exHu: 'Jó estét!' },
  { ru: 'вода', hu: 'víz', level: 'A1', pos: 'főnév', ex: 'Дайте воды, пожалуйста.', exHu: 'Kérek vizet.' },
  { ru: 'хлеб', hu: 'kenyér', level: 'A1', pos: 'főnév', ex: 'Свежий хлеб.', exHu: 'Friss kenyér.' },
  { ru: 'молоко', hu: 'tej', level: 'A1', pos: 'főnév', ex: 'Чай с молоком.', exHu: 'Tea tejjel.' },
  { ru: 'чай', hu: 'tea', level: 'A1', pos: 'főnév', ex: 'Хочешь чай?', exHu: 'Kérsz teát?' },
  { ru: 'кофе', hu: 'kávé', level: 'A1', pos: 'főnév', ex: 'Чёрный кофе.', exHu: 'Fekete kávé.' },
  { ru: 'дом', hu: 'ház / otthon', level: 'A1', pos: 'főnév', ex: 'Я дома.', exHu: 'Otthon vagyok.' },
  { ru: 'город', hu: 'város', level: 'A1', pos: 'főnév', ex: 'Большой город.', exHu: 'Nagy város.' },
  { ru: 'улица', hu: 'utca', level: 'A1', pos: 'főnév', ex: 'На улице холодно.', exHu: 'Kint hideg van.' },
  { ru: 'мама', hu: 'anya', level: 'A1', pos: 'főnév', ex: 'Это моя мама.', exHu: 'Ez az anyukám.' },
  { ru: 'папа', hu: 'apa', level: 'A1', pos: 'főnév', ex: 'Мой папа врач.', exHu: 'Apám orvos.' },
  { ru: 'друг', hu: 'barát', level: 'A1', pos: 'főnév', ex: 'Он мой друг.', exHu: 'Ő a barátom.' },
  { ru: 'человек', hu: 'ember', level: 'A1', pos: 'főnév', ex: 'Хороший человек.', exHu: 'Jó ember.' },
  { ru: 'имя', hu: 'név', level: 'A1', pos: 'főnév', ex: 'Как ваше имя?', exHu: 'Mi a neve?' },
  { ru: 'язык', hu: 'nyelv', level: 'A1', pos: 'főnév', ex: 'Русский язык.', exHu: 'Az orosz nyelv.' },
  { ru: 'книга', hu: 'könyv', level: 'A1', pos: 'főnév', ex: 'Интересная книга.', exHu: 'Érdekes könyv.' },
  { ru: 'стол', hu: 'asztal', level: 'A1', pos: 'főnév', ex: 'Книга на столе.', exHu: 'A könyv az asztalon van.' },
  { ru: 'окно', hu: 'ablak', level: 'A1', pos: 'főnév', ex: 'Открой окно.', exHu: 'Nyisd ki az ablakot.' },
  { ru: 'дверь', hu: 'ajtó', level: 'A1', pos: 'főnév', ex: 'Закрой дверь.', exHu: 'Csukd be az ajtót.' },
  { ru: 'школа', hu: 'iskola', level: 'A1', pos: 'főnév', ex: 'Дети в школе.', exHu: 'A gyerekek az iskolában vannak.' },
  { ru: 'работа', hu: 'munka', level: 'A1', pos: 'főnév', ex: 'Я иду на работу.', exHu: 'Megyek dolgozni.' },
  { ru: 'время', hu: 'idő', level: 'A1', pos: 'főnév', ex: 'Нет времени.', exHu: 'Nincs idő.' },
  { ru: 'год', hu: 'év', level: 'A1', pos: 'főnév', ex: 'Новый год.', exHu: 'Újév.' },
  { ru: 'большой', hu: 'nagy', level: 'A1', pos: 'melléknév', ex: 'Большой дом.', exHu: 'Nagy ház.' },
  { ru: 'маленький', hu: 'kicsi', level: 'A1', pos: 'melléknév', ex: 'Маленький город.', exHu: 'Kis város.' },
  { ru: 'новый', hu: 'új', level: 'A1', pos: 'melléknév', ex: 'Новый телефон.', exHu: 'Új telefon.' },
  { ru: 'старый', hu: 'régi / öreg', level: 'A1', pos: 'melléknév', ex: 'Старый друг.', exHu: 'Régi barát.' },
  { ru: 'хороший', hu: 'jó', level: 'A1', pos: 'melléknév', ex: 'Хороший день.', exHu: 'Jó nap.' },
  { ru: 'быть', hu: 'lenni', level: 'A1', pos: 'ige', ex: 'Я буду дома.', exHu: 'Otthon leszek.' },
  { ru: 'жить', hu: 'élni / lakni', level: 'A1', pos: 'ige', ex: 'Я живу в Москве.', exHu: 'Moszkvában lakom.' },
  { ru: 'знать', hu: 'tudni / ismerni', level: 'A1', pos: 'ige', ex: 'Я не знаю.', exHu: 'Nem tudom.' },
  { ru: 'говорить', hu: 'beszélni', level: 'A1', pos: 'ige', ex: 'Говори медленно.', exHu: 'Beszélj lassan.' },
  { ru: 'читать', hu: 'olvasni', level: 'A1', pos: 'ige', ex: 'Я читаю книгу.', exHu: 'Könyvet olvasok.' },
  { ru: 'писать', hu: 'írni', level: 'A1', pos: 'ige', ex: 'Он пишет письмо.', exHu: 'Levelet ír.' },
  { ru: 'любить', hu: 'szeretni', level: 'A1', pos: 'ige', ex: 'Я люблю тебя.', exHu: 'Szeretlek.' },
  { ru: 'хотеть', hu: 'akarni', level: 'A1', pos: 'ige', ex: 'Я хочу есть.', exHu: 'Enni akarok.' },
  { ru: 'идти', hu: 'menni (gyalog)', level: 'A1', pos: 'ige', ex: 'Я иду домой.', exHu: 'Megyek haza.' },
  { ru: 'есть', hu: 'enni', level: 'A1', pos: 'ige', ex: 'Я хочу есть.', exHu: 'Enni szeretnék.' },
  { ru: 'пить', hu: 'inni', level: 'A1', pos: 'ige', ex: 'Я пью воду.', exHu: 'Vizet iszom.' },
  { ru: 'один', hu: 'egy', level: 'A1', pos: 'számnév', ex: 'Один билет.', exHu: 'Egy jegy.' },
  { ru: 'два', hu: 'kettő', level: 'A1', pos: 'számnév', ex: 'Два кофе.', exHu: 'Két kávé.' },
  { ru: 'три', hu: 'három', level: 'A1', pos: 'számnév', ex: 'Три часа.', exHu: 'Három óra.' },
  { ru: 'сегодня', hu: 'ma', level: 'A1', pos: 'határozószó', ex: 'Сегодня понедельник.', exHu: 'Ma hétfő van.' },
  { ru: 'завтра', hu: 'holnap', level: 'A1', pos: 'határozószó', ex: 'До завтра!', exHu: 'Holnapig!' },

  // ── A2 ──────────────────────────────────────────────────────────────────
  { ru: 'семья', hu: 'család', level: 'A2', pos: 'főnév', ex: 'Большая семья.', exHu: 'Nagy család.' },
  { ru: 'ребёнок', hu: 'gyerek', level: 'A2', pos: 'főnév', ex: 'Маленький ребёнок.', exHu: 'Kisgyerek.' },
  { ru: 'жена', hu: 'feleség', level: 'A2', pos: 'főnév', ex: 'Моя жена учитель.', exHu: 'A feleségem tanár.' },
  { ru: 'муж', hu: 'férj', level: 'A2', pos: 'főnév', ex: 'Её муж инженер.', exHu: 'A férje mérnök.' },
  { ru: 'деньги', hu: 'pénz', level: 'A2', pos: 'főnév', ex: 'У меня нет денег.', exHu: 'Nincs pénzem.' },
  { ru: 'магазин', hu: 'bolt', level: 'A2', pos: 'főnév', ex: 'Иду в магазин.', exHu: 'Megyek a boltba.' },
  { ru: 'еда', hu: 'étel', level: 'A2', pos: 'főnév', ex: 'Вкусная еда.', exHu: 'Finom étel.' },
  { ru: 'ужин', hu: 'vacsora', level: 'A2', pos: 'főnév', ex: 'Ужин готов.', exHu: 'Kész a vacsora.' },
  { ru: 'машина', hu: 'autó', level: 'A2', pos: 'főnév', ex: 'Новая машина.', exHu: 'Új autó.' },
  { ru: 'поезд', hu: 'vonat', level: 'A2', pos: 'főnév', ex: 'Поезд опаздывает.', exHu: 'A vonat késik.' },
  { ru: 'самолёт', hu: 'repülőgép', level: 'A2', pos: 'főnév', ex: 'Самолёт в Москву.', exHu: 'Repülő Moszkvába.' },
  { ru: 'билет', hu: 'jegy', level: 'A2', pos: 'főnév', ex: 'Два билета, пожалуйста.', exHu: 'Két jegyet kérek.' },
  { ru: 'погода', hu: 'időjárás', level: 'A2', pos: 'főnév', ex: 'Хорошая погода.', exHu: 'Jó idő van.' },
  { ru: 'зима', hu: 'tél', level: 'A2', pos: 'főnév', ex: 'Холодная зима.', exHu: 'Hideg tél.' },
  { ru: 'лето', hu: 'nyár', level: 'A2', pos: 'főnév', ex: 'Жаркое лето.', exHu: 'Forró nyár.' },
  { ru: 'вопрос', hu: 'kérdés', level: 'A2', pos: 'főnév', ex: 'Хороший вопрос.', exHu: 'Jó kérdés.' },
  { ru: 'ответ', hu: 'válasz', level: 'A2', pos: 'főnév', ex: 'Правильный ответ.', exHu: 'Helyes válasz.' },
  { ru: 'слово', hu: 'szó', level: 'A2', pos: 'főnév', ex: 'Новое слово.', exHu: 'Új szó.' },
  { ru: 'работать', hu: 'dolgozni', level: 'A2', pos: 'ige', ex: 'Я работаю в офисе.', exHu: 'Irodában dolgozom.' },
  { ru: 'учиться', hu: 'tanulni', level: 'A2', pos: 'ige', ex: 'Я учусь в университете.', exHu: 'Egyetemen tanulok.' },
  { ru: 'понимать', hu: 'érteni', level: 'A2', pos: 'ige', ex: 'Я понимаю.', exHu: 'Értem.' },
  { ru: 'помнить', hu: 'emlékezni', level: 'A2', pos: 'ige', ex: 'Я не помню.', exHu: 'Nem emlékszem.' },
  { ru: 'видеть', hu: 'látni', level: 'A2', pos: 'ige', ex: 'Я вижу море.', exHu: 'Látom a tengert.' },
  { ru: 'слышать', hu: 'hallani', level: 'A2', pos: 'ige', ex: 'Ты слышишь меня?', exHu: 'Hallasz engem?' },
  { ru: 'ждать', hu: 'várni', level: 'A2', pos: 'ige', ex: 'Я жду автобус.', exHu: 'A buszra várok.' },
  { ru: 'давать', hu: 'adni', level: 'A2', pos: 'ige', ex: 'Дай мне ручку.', exHu: 'Adj egy tollat.' },
  { ru: 'покупать', hu: 'venni / vásárolni', level: 'A2', pos: 'ige', ex: 'Я покупаю хлеб.', exHu: 'Kenyeret veszek.' },
  { ru: 'открывать', hu: 'kinyitni', level: 'A2', pos: 'ige', ex: 'Магазин открывается в восемь.', exHu: 'A bolt nyolckor nyit.' },
  { ru: 'помогать', hu: 'segíteni', level: 'A2', pos: 'ige', ex: 'Помоги мне, пожалуйста.', exHu: 'Segíts, kérlek.' },
  { ru: 'спрашивать', hu: 'kérdezni', level: 'A2', pos: 'ige', ex: 'Он спрашивает дорогу.', exHu: 'Az utat kérdezi.' },
  { ru: 'отвечать', hu: 'válaszolni', level: 'A2', pos: 'ige', ex: 'Отвечай на вопрос.', exHu: 'Válaszolj a kérdésre.' },
  { ru: 'красивый', hu: 'szép', level: 'A2', pos: 'melléknév', ex: 'Красивый город.', exHu: 'Szép város.' },
  { ru: 'трудный', hu: 'nehéz (feladat)', level: 'A2', pos: 'melléknév', ex: 'Трудный вопрос.', exHu: 'Nehéz kérdés.' },
  { ru: 'лёгкий', hu: 'könnyű', level: 'A2', pos: 'melléknév', ex: 'Лёгкий текст.', exHu: 'Könnyű szöveg.' },
  { ru: 'быстрый', hu: 'gyors', level: 'A2', pos: 'melléknév', ex: 'Быстрый поезд.', exHu: 'Gyors vonat.' },
  { ru: 'медленный', hu: 'lassú', level: 'A2', pos: 'melléknév', ex: 'Медленный интернет.', exHu: 'Lassú internet.' },
  { ru: 'важный', hu: 'fontos', level: 'A2', pos: 'melléknév', ex: 'Важный день.', exHu: 'Fontos nap.' },
  { ru: 'интересный', hu: 'érdekes', level: 'A2', pos: 'melléknév', ex: 'Интересный фильм.', exHu: 'Érdekes film.' },
  { ru: 'дорогой', hu: 'drága', level: 'A2', pos: 'melléknév', ex: 'Дорогой ресторан.', exHu: 'Drága étterem.' },
  { ru: 'дешёвый', hu: 'olcsó', level: 'A2', pos: 'melléknév', ex: 'Дешёвый билет.', exHu: 'Olcsó jegy.' },
  { ru: 'сейчас', hu: 'most', level: 'A2', pos: 'határozószó', ex: 'Я занят сейчас.', exHu: 'Most elfoglalt vagyok.' },
  { ru: 'потом', hu: 'aztán / később', level: 'A2', pos: 'határozószó', ex: 'Поговорим потом.', exHu: 'Később beszélünk.' },
  { ru: 'всегда', hu: 'mindig', level: 'A2', pos: 'határozószó', ex: 'Он всегда опаздывает.', exHu: 'Mindig késik.' },
  { ru: 'никогда', hu: 'soha', level: 'A2', pos: 'határozószó', ex: 'Я никогда не был там.', exHu: 'Soha nem voltam ott.' },
  { ru: 'часто', hu: 'gyakran', level: 'A2', pos: 'határozószó', ex: 'Я часто читаю.', exHu: 'Gyakran olvasok.' },
  { ru: 'редко', hu: 'ritkán', level: 'A2', pos: 'határozószó', ex: 'Мы редко видимся.', exHu: 'Ritkán találkozunk.' },
  { ru: 'здесь', hu: 'itt', level: 'A2', pos: 'határozószó', ex: 'Подожди здесь.', exHu: 'Várj itt.' },
  { ru: 'там', hu: 'ott', level: 'A2', pos: 'határozószó', ex: 'Он там.', exHu: 'Ott van.' },

  // ── B1 ──────────────────────────────────────────────────────────────────
  { ru: 'общество', hu: 'társadalom', level: 'B1', pos: 'főnév', ex: 'Современное общество.', exHu: 'A modern társadalom.' },
  { ru: 'правительство', hu: 'kormány', level: 'B1', pos: 'főnév', ex: 'Новое правительство.', exHu: 'Új kormány.' },
  { ru: 'здоровье', hu: 'egészség', level: 'B1', pos: 'főnév', ex: 'Береги здоровье.', exHu: 'Vigyázz az egészségedre.' },
  { ru: 'болезнь', hu: 'betegség', level: 'B1', pos: 'főnév', ex: 'Серьёзная болезнь.', exHu: 'Súlyos betegség.' },
  { ru: 'образование', hu: 'oktatás', level: 'B1', pos: 'főnév', ex: 'Высшее образование.', exHu: 'Felsőoktatás.' },
  { ru: 'опыт', hu: 'tapasztalat', level: 'B1', pos: 'főnév', ex: 'Большой опыт.', exHu: 'Nagy tapasztalat.' },
  { ru: 'решение', hu: 'döntés / megoldás', level: 'B1', pos: 'főnév', ex: 'Трудное решение.', exHu: 'Nehéz döntés.' },
  { ru: 'проблема', hu: 'probléma', level: 'B1', pos: 'főnév', ex: 'Серьёзная проблема.', exHu: 'Komoly probléma.' },
  { ru: 'причина', hu: 'ok', level: 'B1', pos: 'főnév', ex: 'В чём причина?', exHu: 'Mi az ok?' },
  { ru: 'цель', hu: 'cél', level: 'B1', pos: 'főnév', ex: 'Наша главная цель.', exHu: 'A fő célunk.' },
  { ru: 'возможность', hu: 'lehetőség', level: 'B1', pos: 'főnév', ex: 'Хорошая возможность.', exHu: 'Jó lehetőség.' },
  { ru: 'развитие', hu: 'fejlődés', level: 'B1', pos: 'főnév', ex: 'Быстрое развитие.', exHu: 'Gyors fejlődés.' },
  { ru: 'природа', hu: 'természet', level: 'B1', pos: 'főnév', ex: 'Красивая природа.', exHu: 'Gyönyörű természet.' },
  { ru: 'искусство', hu: 'művészet', level: 'B1', pos: 'főnév', ex: 'Современное искусство.', exHu: 'Modern művészet.' },
  { ru: 'наука', hu: 'tudomány', level: 'B1', pos: 'főnév', ex: 'Наука и техника.', exHu: 'Tudomány és technika.' },
  { ru: 'закон', hu: 'törvény', level: 'B1', pos: 'főnév', ex: 'Новый закон.', exHu: 'Új törvény.' },
  { ru: 'изменять', hu: 'megváltoztatni', level: 'B1', pos: 'ige', ex: 'Трудно изменить привычки.', exHu: 'Nehéz megváltoztatni a szokásokat.' },
  { ru: 'развивать', hu: 'fejleszteni', level: 'B1', pos: 'ige', ex: 'Развивать навыки.', exHu: 'Készségeket fejleszteni.' },
  { ru: 'создавать', hu: 'létrehozni', level: 'B1', pos: 'ige', ex: 'Создавать проекты.', exHu: 'Projekteket létrehozni.' },
  { ru: 'решать', hu: 'megoldani / dönteni', level: 'B1', pos: 'ige', ex: 'Решать проблемы.', exHu: 'Problémákat megoldani.' },
  { ru: 'предлагать', hu: 'javasolni', level: 'B1', pos: 'ige', ex: 'Я предлагаю встретиться.', exHu: 'Javaslom, hogy találkozzunk.' },
  { ru: 'получать', hu: 'kapni', level: 'B1', pos: 'ige', ex: 'Получать зарплату.', exHu: 'Fizetést kapni.' },
  { ru: 'использовать', hu: 'használni', level: 'B1', pos: 'ige', ex: 'Использовать компьютер.', exHu: 'Számítógépet használni.' },
  { ru: 'считать', hu: 'gondolni / számolni', level: 'B1', pos: 'ige', ex: 'Я считаю, что он прав.', exHu: 'Úgy gondolom, igaza van.' },
  { ru: 'объяснять', hu: 'megmagyarázni', level: 'B1', pos: 'ige', ex: 'Объясни правило.', exHu: 'Magyarázd el a szabályt.' },
  { ru: 'происходить', hu: 'történni', level: 'B1', pos: 'ige', ex: 'Что происходит?', exHu: 'Mi történik?' },
  { ru: 'зависеть', hu: 'függeni', level: 'B1', pos: 'ige', ex: 'Это зависит от тебя.', exHu: 'Ez tőled függ.' },
  { ru: 'современный', hu: 'modern / mai', level: 'B1', pos: 'melléknév', ex: 'Современная музыка.', exHu: 'Mai zene.' },
  { ru: 'возможный', hu: 'lehetséges', level: 'B1', pos: 'melléknév', ex: 'Это возможно.', exHu: 'Ez lehetséges.' },
  { ru: 'необходимый', hu: 'szükséges', level: 'B1', pos: 'melléknév', ex: 'Необходимый шаг.', exHu: 'Szükséges lépés.' },
  { ru: 'известный', hu: 'ismert / híres', level: 'B1', pos: 'melléknév', ex: 'Известный писатель.', exHu: 'Ismert író.' },
  { ru: 'разный', hu: 'különböző', level: 'B1', pos: 'melléknév', ex: 'Разные мнения.', exHu: 'Különböző vélemények.' },
  { ru: 'обычно', hu: 'általában', level: 'B1', pos: 'határozószó', ex: 'Обычно я встаю рано.', exHu: 'Általában korán kelek.' },
  { ru: 'например', hu: 'például', level: 'B1', pos: 'határozószó', ex: 'Например, вода.', exHu: 'Például a víz.' },
  { ru: 'поэтому', hu: 'ezért', level: 'B1', pos: 'kötőszó', ex: 'Идёт дождь, поэтому я дома.', exHu: 'Esik, ezért otthon vagyok.' },
  { ru: 'хотя', hu: 'bár / habár', level: 'B1', pos: 'kötőszó', ex: 'Хотя было поздно, он пришёл.', exHu: 'Bár késő volt, eljött.' },
  { ru: 'кажется', hu: 'úgy tűnik', level: 'B1', pos: 'kifejezés', ex: 'Кажется, идёт дождь.', exHu: 'Úgy tűnik, esik.' },

  // ── B2 ──────────────────────────────────────────────────────────────────
  { ru: 'впечатление', hu: 'benyomás', level: 'B2', pos: 'főnév', ex: 'Хорошее впечатление.', exHu: 'Jó benyomás.' },
  { ru: 'преимущество', hu: 'előny', level: 'B2', pos: 'főnév', ex: 'Большое преимущество.', exHu: 'Nagy előny.' },
  { ru: 'недостаток', hu: 'hátrány / hiányosság', level: 'B2', pos: 'főnév', ex: 'Главный недостаток.', exHu: 'A fő hátrány.' },
  { ru: 'отношение', hu: 'viszony / kapcsolat', level: 'B2', pos: 'főnév', ex: 'Хорошие отношения.', exHu: 'Jó kapcsolat.' },
  { ru: 'ответственность', hu: 'felelősség', level: 'B2', pos: 'főnév', ex: 'Большая ответственность.', exHu: 'Nagy felelősség.' },
  { ru: 'внимание', hu: 'figyelem', level: 'B2', pos: 'főnév', ex: 'Обрати внимание.', exHu: 'Figyelj oda.' },
  { ru: 'уровень', hu: 'szint', level: 'B2', pos: 'főnév', ex: 'Высокий уровень.', exHu: 'Magas szint.' },
  { ru: 'состояние', hu: 'állapot', level: 'B2', pos: 'főnév', ex: 'Плохое состояние.', exHu: 'Rossz állapot.' },
  { ru: 'событие', hu: 'esemény', level: 'B2', pos: 'főnév', ex: 'Важное событие.', exHu: 'Fontos esemény.' },
  { ru: 'значение', hu: 'jelentés / jelentőség', level: 'B2', pos: 'főnév', ex: 'Большое значение.', exHu: 'Nagy jelentőség.' },
  { ru: 'достигать', hu: 'elérni', level: 'B2', pos: 'ige', ex: 'Достигать цели.', exHu: 'Elérni a célt.' },
  { ru: 'обеспечивать', hu: 'biztosítani', level: 'B2', pos: 'ige', ex: 'Обеспечивать безопасность.', exHu: 'Biztosítani a biztonságot.' },
  { ru: 'требовать', hu: 'követelni / igényelni', level: 'B2', pos: 'ige', ex: 'Это требует времени.', exHu: 'Ez időt igényel.' },
  { ru: 'предпочитать', hu: 'előnyben részesíteni', level: 'B2', pos: 'ige', ex: 'Я предпочитаю чай.', exHu: 'A teát részesítem előnyben.' },
  { ru: 'учитывать', hu: 'figyelembe venni', level: 'B2', pos: 'ige', ex: 'Учитывать все факторы.', exHu: 'Minden tényezőt figyelembe venni.' },
  { ru: 'оценивать', hu: 'értékelni / felmérni', level: 'B2', pos: 'ige', ex: 'Оценивать ситуацию.', exHu: 'Felmérni a helyzetet.' },
  { ru: 'признавать', hu: 'elismerni', level: 'B2', pos: 'ige', ex: 'Признавать ошибку.', exHu: 'Beismerni a hibát.' },
  { ru: 'стремиться', hu: 'törekedni', level: 'B2', pos: 'ige', ex: 'Стремиться к успеху.', exHu: 'A sikerre törekedni.' },
  { ru: 'сомневаться', hu: 'kételkedni', level: 'B2', pos: 'ige', ex: 'Я сомневаюсь в этом.', exHu: 'Kételkedem ebben.' },
  { ru: 'значительный', hu: 'jelentős', level: 'B2', pos: 'melléknév', ex: 'Значительный успех.', exHu: 'Jelentős siker.' },
  { ru: 'подобный', hu: 'hasonló', level: 'B2', pos: 'melléknév', ex: 'Подобный случай.', exHu: 'Hasonló eset.' },
  { ru: 'очевидный', hu: 'nyilvánvaló', level: 'B2', pos: 'melléknév', ex: 'Очевидный ответ.', exHu: 'Nyilvánvaló válasz.' },
  { ru: 'достаточный', hu: 'elegendő', level: 'B2', pos: 'melléknév', ex: 'Достаточный опыт.', exHu: 'Elegendő tapasztalat.' },
  { ru: 'сложный', hu: 'bonyolult', level: 'B2', pos: 'melléknév', ex: 'Сложный вопрос.', exHu: 'Bonyolult kérdés.' },
  { ru: 'напротив', hu: 'ellenkezőleg / szemben', level: 'B2', pos: 'határozószó', ex: 'Напротив, я согласен.', exHu: 'Ellenkezőleg, egyetértek.' },
  { ru: 'вероятно', hu: 'valószínűleg', level: 'B2', pos: 'határozószó', ex: 'Вероятно, он прав.', exHu: 'Valószínűleg igaza van.' },
  { ru: 'кроме того', hu: 'ráadásul', level: 'B2', pos: 'kifejezés', ex: 'Кроме того, это дёшево.', exHu: 'Ráadásul olcsó.' },
  { ru: 'несмотря на', hu: 'ellenére', level: 'B2', pos: 'kifejezés', ex: 'Несмотря на дождь, мы гуляли.', exHu: 'Az eső ellenére sétáltunk.' },

  // ── C1 ──────────────────────────────────────────────────────────────────
  { ru: 'закономерность', hu: 'törvényszerűség', level: 'C1', pos: 'főnév', ex: 'Определённая закономерность.', exHu: 'Bizonyos törvényszerűség.' },
  { ru: 'противоречие', hu: 'ellentmondás', level: 'C1', pos: 'főnév', ex: 'Явное противоречие.', exHu: 'Nyilvánvaló ellentmondás.' },
  { ru: 'обстоятельство', hu: 'körülmény', level: 'C1', pos: 'főnév', ex: 'При любых обстоятельствах.', exHu: 'Bármilyen körülmények között.' },
  { ru: 'преодоление', hu: 'leküzdés', level: 'C1', pos: 'főnév', ex: 'Преодоление трудностей.', exHu: 'A nehézségek leküzdése.' },
  { ru: 'восприятие', hu: 'észlelés / felfogás', level: 'C1', pos: 'főnév', ex: 'Восприятие мира.', exHu: 'A világ felfogása.' },
  { ru: 'подход', hu: 'megközelítés', level: 'C1', pos: 'főnév', ex: 'Новый подход.', exHu: 'Új megközelítés.' },
  { ru: 'сущность', hu: 'lényeg', level: 'C1', pos: 'főnév', ex: 'Сущность проблемы.', exHu: 'A probléma lényege.' },
  { ru: 'осуществлять', hu: 'megvalósítani', level: 'C1', pos: 'ige', ex: 'Осуществлять план.', exHu: 'Megvalósítani a tervet.' },
  { ru: 'подчёркивать', hu: 'hangsúlyozni', level: 'C1', pos: 'ige', ex: 'Подчёркивать важность.', exHu: 'Hangsúlyozni a fontosságot.' },
  { ru: 'предполагать', hu: 'feltételezni', level: 'C1', pos: 'ige', ex: 'Можно предположить, что...', exHu: 'Feltételezhető, hogy...' },
  { ru: 'соответствовать', hu: 'megfelelni', level: 'C1', pos: 'ige', ex: 'Соответствовать требованиям.', exHu: 'Megfelelni a követelményeknek.' },
  { ru: 'опровергать', hu: 'megcáfolni', level: 'C1', pos: 'ige', ex: 'Опровергать теорию.', exHu: 'Megcáfolni az elméletet.' },
  { ru: 'способствовать', hu: 'elősegíteni', level: 'C1', pos: 'ige', ex: 'Способствовать развитию.', exHu: 'Elősegíteni a fejlődést.' },
  { ru: 'воспринимать', hu: 'felfogni / érzékelni', level: 'C1', pos: 'ige', ex: 'Воспринимать критику.', exHu: 'Fogadni a kritikát.' },
  { ru: 'существенный', hu: 'lényeges', level: 'C1', pos: 'melléknév', ex: 'Существенная разница.', exHu: 'Lényeges különbség.' },
  { ru: 'неизбежный', hu: 'elkerülhetetlen', level: 'C1', pos: 'melléknév', ex: 'Неизбежный результат.', exHu: 'Elkerülhetetlen eredmény.' },
  { ru: 'противоречивый', hu: 'ellentmondásos', level: 'C1', pos: 'melléknév', ex: 'Противоречивые данные.', exHu: 'Ellentmondásos adatok.' },
  { ru: 'целесообразный', hu: 'célszerű', level: 'C1', pos: 'melléknév', ex: 'Целесообразное решение.', exHu: 'Célszerű döntés.' },
  { ru: 'тем не менее', hu: 'mindazonáltal', level: 'C1', pos: 'kifejezés', ex: 'Тем не менее, я согласен.', exHu: 'Mindazonáltal egyetértek.' },
  { ru: 'вследствие', hu: 'következtében', level: 'C1', pos: 'elöljárószó', ex: 'Вследствие ошибки.', exHu: 'Egy hiba következtében.' },

  // ── C2 ──────────────────────────────────────────────────────────────────
  { ru: 'многогранность', hu: 'sokrétűség', level: 'C2', pos: 'főnév', ex: 'Многогранность таланта.', exHu: 'A tehetség sokrétűsége.' },
  { ru: 'самобытность', hu: 'egyediség / eredetiség', level: 'C2', pos: 'főnév', ex: 'Культурная самобытность.', exHu: 'Kulturális eredetiség.' },
  { ru: 'проницательность', hu: 'éleslátás', level: 'C2', pos: 'főnév', ex: 'Редкая проницательность.', exHu: 'Ritka éleslátás.' },
  { ru: 'изощрённость', hu: 'kifinomultság', level: 'C2', pos: 'főnév', ex: 'Изощрённость стиля.', exHu: 'A stílus kifinomultsága.' },
  { ru: 'беспристрастность', hu: 'pártatlanság', level: 'C2', pos: 'főnév', ex: 'Полная беспристрастность.', exHu: 'Teljes pártatlanság.' },
  { ru: 'подоплёка', hu: 'háttér / rejtett ok', level: 'C2', pos: 'főnév', ex: 'Скрытая подоплёка.', exHu: 'Rejtett háttér.' },
  { ru: 'усугублять', hu: 'súlyosbítani', level: 'C2', pos: 'ige', ex: 'Усугублять положение.', exHu: 'Súlyosbítani a helyzetet.' },
  { ru: 'изобиловать', hu: 'bővelkedni', level: 'C2', pos: 'ige', ex: 'Текст изобилует ошибками.', exHu: 'A szöveg hemzseg a hibáktól.' },
  { ru: 'сподвигнуть', hu: 'ösztönözni (tettre)', level: 'C2', pos: 'ige', ex: 'Это сподвигло его на перемены.', exHu: 'Ez változásra ösztönözte.' },
  { ru: 'нивелировать', hu: 'kiegyenlíteni / semlegesíteni', level: 'C2', pos: 'ige', ex: 'Нивелировать различия.', exHu: 'Kiegyenlíteni a különbségeket.' },
  { ru: 'скрупулёзный', hu: 'aprólékos / precíz', level: 'C2', pos: 'melléknév', ex: 'Скрупулёзный анализ.', exHu: 'Aprólékos elemzés.' },
  { ru: 'изощрённый', hu: 'kifinomult / agyafúrt', level: 'C2', pos: 'melléknév', ex: 'Изощрённый план.', exHu: 'Agyafúrt terv.' },
  { ru: 'опрометчивый', hu: 'meggondolatlan', level: 'C2', pos: 'melléknév', ex: 'Опрометчивое решение.', exHu: 'Meggondolatlan döntés.' },
  { ru: 'самодостаточный', hu: 'önellátó / önmagában elég', level: 'C2', pos: 'melléknév', ex: 'Самодостаточный человек.', exHu: 'Önmagában elégedett ember.' },
  { ru: 'зачастую', hu: 'gyakorta', level: 'C2', pos: 'határozószó', ex: 'Зачастую это так.', exHu: 'Gyakorta így van.' },
  { ru: 'впредь', hu: 'ezentúl', level: 'C2', pos: 'határozószó', ex: 'Впредь будь осторожен.', exHu: 'Ezentúl légy óvatos.' },
];

// Word groups (topic / grammar), each referencing words from RU_WORDS by `ru`.
window.RU_GROUPS = [
  { id: 'greetings', cat: 'topic', icon: '👋', title: 'Üdvözlések', words: ['привет', 'пока', 'здравствуйте', 'спасибо', 'пожалуйста', 'извините', 'да', 'нет'] },
  { id: 'family', cat: 'topic', icon: '👪', title: 'Család', words: ['семья', 'ребёнок', 'жена', 'муж', 'мама', 'папа', 'друг', 'человек'] },
  { id: 'fooddrink', cat: 'topic', icon: '🍎', title: 'Étel és ital', words: ['еда', 'ужин', 'хлеб', 'молоко', 'вода', 'чай', 'кофе'] },
  { id: 'home', cat: 'topic', icon: '🏠', title: 'Otthon és város', words: ['дом', 'город', 'улица', 'школа', 'работа', 'магазин', 'окно', 'дверь', 'стол'] },
  { id: 'time', cat: 'topic', icon: '⏰', title: 'Idő', words: ['день', 'ночь', 'утро', 'вечер', 'время', 'год', 'сегодня', 'завтра', 'сейчас', 'потом'] },
  { id: 'travel', cat: 'topic', icon: '✈️', title: 'Utazás', words: ['машина', 'поезд', 'самолёт', 'билет', 'город'] },
  { id: 'nature', cat: 'topic', icon: '🌳', title: 'Természet és időjárás', words: ['природа', 'погода', 'зима', 'лето'] },
  { id: 'questions', cat: 'grammar', icon: '❓', title: 'Kérdőszavak', words: ['кто', 'что', 'где', 'когда', 'как', 'почему'] },
  { id: 'numbers', cat: 'grammar', icon: '🔢', title: 'Számok', words: ['один', 'два', 'три'] },
  { id: 'pronouns', cat: 'grammar', icon: '🧑', title: 'Névmások', words: ['я', 'ты', 'он', 'она', 'мы', 'вы', 'они', 'это'] },
  { id: 'verbs_basic', cat: 'grammar', icon: '🅰️', title: 'Alap igék', words: ['быть', 'жить', 'знать', 'говорить', 'читать', 'писать', 'любить', 'хотеть', 'идти', 'есть', 'пить', 'работать', 'понимать', 'видеть'] },
  { id: 'adjectives', cat: 'grammar', icon: '✨', title: 'Melléknevek', words: ['большой', 'маленький', 'новый', 'старый', 'хороший', 'красивый', 'трудный', 'лёгкий', 'быстрый', 'медленный', 'важный', 'интересный', 'дорогой', 'дешёвый'] },
];
