// Curated Russian (learned) -> Hungarian (native) starter vocabulary.
// Each entry: ru (word), hu (meaning), level (A1..C2), pos, ex (Russian example),
// exHu (Hungarian translation of the example). Examples are kept short and simple.
// Easy to extend: just add more objects. Exposed as window.RU_WORDS.

window.RU_WORDS = [
  // ── A1 ──────────────────────────────────────────────────────────────────
  { ru: 'привет', hu: 'szia', level: 'A1', pos: 'indulatszó', ex: 'Привет, как дела?', exHu: 'Szia, hogy vagy?' },
  { ru: 'пока', hu: 'szia (viszlát)', level: 'A1', pos: 'indulatszó', ex: 'Пока, до завтра!', exHu: 'Szia, holnapig!' },
  { ru: 'здравствуйте', hu: 'jó napot (üdvözlés)', level: 'A1', pos: 'indulatszó', ex: 'Здравствуйте, я Анна.', exHu: 'Jó napot, Anna vagyok.' },
  { ru: 'спасибо', hu: 'köszönöm', level: 'A1', pos: 'indulatszó', ex: 'Спасибо большое!', exHu: 'Nagyon köszönöm!' },
  { ru: 'пожалуйста', hu: 'kérlek / szívesen', level: 'A1', pos: 'indulatszó', ex: 'Кофе, пожалуйста.', exHu: 'Egy kávét kérek.' },
  { ru: 'извините', hu: 'elnézést', level: 'A1', pos: 'indulatszó', ex: 'Извините, где метро?', exHu: 'Elnézést, hol a metró?' },
  { ru: 'да', hu: 'igen', level: 'A1', pos: 'partikula', ex: 'Да, конечно.', exHu: 'Igen, persze.' },
  { ru: 'нет', hu: 'nem', level: 'A1', pos: 'partikula', ex: 'Нет, спасибо.', exHu: 'Nem, köszönöm.' },
  { ru: 'я', hu: 'én', level: 'A1', pos: 'névmás', ex: 'Я студент.', exHu: 'Diák vagyok.' },
  { ru: 'ты', hu: 'te', level: 'A1', pos: 'névmás', ex: 'Ты дома?', exHu: 'Otthon vagy?' },
  { ru: 'он', hu: 'ő (hímnem)', level: 'A1', pos: 'névmás', ex: 'Он мой брат.', exHu: 'Ő a bátyám.' },
  { ru: 'она', hu: 'ő (nőnem)', level: 'A1', pos: 'névmás', ex: 'Она врач.', exHu: 'Ő orvos.' },
  { ru: 'мы', hu: 'mi', level: 'A1', pos: 'névmás', ex: 'Мы друзья.', exHu: 'Barátok vagyunk.' },
  { ru: 'вы', hu: 'ti / ön', level: 'A1', pos: 'névmás', ex: 'Вы говорите по-русски?', exHu: 'Beszél oroszul?' },
  { ru: 'они', hu: 'ők', level: 'A1', pos: 'névmás', ex: 'Они здесь.', exHu: 'Itt vannak.' },
  { ru: 'это', hu: 'ez', level: 'A1', pos: 'névmás', ex: 'Это книга.', exHu: 'Ez egy könyv.' },
  { ru: 'кто', hu: 'ki', level: 'A1', pos: 'névmás', ex: 'Кто это?', exHu: 'Ki ez?' },
  { ru: 'что', hu: 'mi / mit', level: 'A1', pos: 'névmás', ex: 'Что это?', exHu: 'Ez mi?' },
  { ru: 'где', hu: 'hol', level: 'A1', pos: 'határozószó', ex: 'Где ты?', exHu: 'Hol vagy?' },
  { ru: 'когда', hu: 'mikor', level: 'A1', pos: 'határozószó', ex: 'Когда урок?', exHu: 'Mikor van az óra?' },
  { ru: 'как', hu: 'hogyan', level: 'A1', pos: 'határozószó', ex: 'Как тебя зовут?', exHu: 'Hogy hívnak?' },
  { ru: 'почему', hu: 'miért', level: 'A1', pos: 'határozószó', ex: 'Почему нет?', exHu: 'Miért nem?' },
  { ru: 'хорошо', hu: 'jól / rendben', level: 'A1', pos: 'határozószó', ex: 'Всё хорошо.', exHu: 'Minden rendben.' },
  { ru: 'плохо', hu: 'rosszul', level: 'A1', pos: 'határozószó', ex: 'Мне плохо.', exHu: 'Rosszul vagyok.' },
  { ru: 'день', hu: 'nap (napszak)', level: 'A1', pos: 'főnév', ex: 'Добрый день!', exHu: 'Jó napot!' },
  { ru: 'ночь', hu: 'éjszaka', level: 'A1', pos: 'főnév', ex: 'Спокойной ночи.', exHu: 'Jó éjszakát.' },
  { ru: 'утро', hu: 'reggel', level: 'A1', pos: 'főnév', ex: 'Доброе утро!', exHu: 'Jó reggelt!' },
  { ru: 'вечер', hu: 'este', level: 'A1', pos: 'főnév', ex: 'Добрый вечер!', exHu: 'Jó estét!' },
  { ru: 'вода', hu: 'víz', level: 'A1', pos: 'főnév', ex: 'Дайте воды, пожалуйста.', exHu: 'Kérek vizet.' },
  { ru: 'хлеб', hu: 'kenyér', level: 'A1', pos: 'főnév', ex: 'Свежий хлеб.', exHu: 'Friss kenyér.' },
  { ru: 'молоко', hu: 'tej', level: 'A1', pos: 'főnév', ex: 'Чай с молоком.', exHu: 'Tea tejjel.' },
  { ru: 'чай', hu: 'tea', level: 'A1', pos: 'főnév', ex: 'Хочешь чай?', exHu: 'Kérsz teát?' },
  { ru: 'кофе', hu: 'kávé', level: 'A1', pos: 'főnév', ex: 'Чёрный кофе.', exHu: 'Fekete kávé.' },
  { ru: 'дом', hu: 'ház / otthon', level: 'A1', pos: 'főnév', ex: 'Я дома.', exHu: 'Otthon vagyok.' },
  { ru: 'город', hu: 'város', level: 'A1', pos: 'főnév', ex: 'Большой город.', exHu: 'Nagy város.' },
  { ru: 'улица', hu: 'utca', level: 'A1', pos: 'főnév', ex: 'На улице холодно.', exHu: 'Kint hideg van.' },
  { ru: 'мама', hu: 'anya', level: 'A1', pos: 'főnév', ex: 'Это моя мама.', exHu: 'Ez az anyukám.' },
  { ru: 'папа', hu: 'apa', level: 'A1', pos: 'főnév', ex: 'Мой папа врач.', exHu: 'Apám orvos.' },
  { ru: 'друг', hu: 'barát', level: 'A1', pos: 'főnév', ex: 'Он мой друг.', exHu: 'Ő a barátom.' },
  { ru: 'человек', hu: 'ember', level: 'A1', pos: 'főnév', ex: 'Хороший человек.', exHu: 'Jó ember.' },
  { ru: 'имя', hu: 'név', level: 'A1', pos: 'főnév', ex: 'Как ваше имя?', exHu: 'Mi a neve?' },
  { ru: 'язык', hu: 'nyelv', level: 'A1', pos: 'főnév', ex: 'Русский язык.', exHu: 'Az orosz nyelv.' },
  { ru: 'книга', hu: 'könyv', level: 'A1', pos: 'főnév', ex: 'Интересная книга.', exHu: 'Érdekes könyv.' },
  { ru: 'стол', hu: 'asztal', level: 'A1', pos: 'főnév', ex: 'Книга на столе.', exHu: 'A könyv az asztalon van.' },
  { ru: 'окно', hu: 'ablak', level: 'A1', pos: 'főnév', ex: 'Открой окно.', exHu: 'Nyisd ki az ablakot.' },
  { ru: 'дверь', hu: 'ajtó', level: 'A1', pos: 'főnév', ex: 'Закрой дверь.', exHu: 'Csukd be az ajtót.' },
  { ru: 'школа', hu: 'iskola', level: 'A1', pos: 'főnév', ex: 'Дети в школе.', exHu: 'A gyerekek az iskolában vannak.' },
  { ru: 'работа', hu: 'munka', level: 'A1', pos: 'főnév', ex: 'Я иду на работу.', exHu: 'Megyek dolgozni.' },
  { ru: 'время', hu: 'idő', level: 'A1', pos: 'főnév', ex: 'Нет времени.', exHu: 'Nincs idő.' },
  { ru: 'год', hu: 'év', level: 'A1', pos: 'főnév', ex: 'Новый год.', exHu: 'Újév.' },
  { ru: 'большой', hu: 'nagy', level: 'A1', pos: 'melléknév', ex: 'Большой дом.', exHu: 'Nagy ház.' },
  { ru: 'маленький', hu: 'kicsi', level: 'A1', pos: 'melléknév', ex: 'Маленький город.', exHu: 'Kis város.' },
  { ru: 'новый', hu: 'új', level: 'A1', pos: 'melléknév', ex: 'Новый телефон.', exHu: 'Új telefon.' },
  { ru: 'старый', hu: 'régi / öreg', level: 'A1', pos: 'melléknév', ex: 'Старый друг.', exHu: 'Régi barát.' },
  { ru: 'хороший', hu: 'jó', level: 'A1', pos: 'melléknév', ex: 'Хороший день.', exHu: 'Jó nap.' },
  { ru: 'быть', hu: 'lenni', level: 'A1', pos: 'ige', ex: 'Я буду дома.', exHu: 'Otthon leszek.' },
  { ru: 'жить', hu: 'élni / lakni', level: 'A1', pos: 'ige', ex: 'Я живу в Москве.', exHu: 'Moszkvában lakom.' },
  { ru: 'знать', hu: 'tudni / ismerni', level: 'A1', pos: 'ige', ex: 'Я не знаю.', exHu: 'Nem tudom.' },
  { ru: 'говорить', hu: 'beszélni', level: 'A1', pos: 'ige', ex: 'Говори медленно.', exHu: 'Beszélj lassan.' },
  { ru: 'читать', hu: 'olvasni', level: 'A1', pos: 'ige', ex: 'Я читаю книгу.', exHu: 'Könyvet olvasok.' },
  { ru: 'писать', hu: 'írni', level: 'A1', pos: 'ige', ex: 'Он пишет письмо.', exHu: 'Levelet ír.' },
  { ru: 'любить', hu: 'szeretni', level: 'A1', pos: 'ige', ex: 'Я люблю тебя.', exHu: 'Szeretlek.' },
  { ru: 'хотеть', hu: 'akarni', level: 'A1', pos: 'ige', ex: 'Я хочу есть.', exHu: 'Enni akarok.' },
  { ru: 'идти', hu: 'menni (gyalog)', level: 'A1', pos: 'ige', ex: 'Я иду домой.', exHu: 'Megyek haza.' },
  { ru: 'есть', hu: 'enni', level: 'A1', pos: 'ige', ex: 'Я хочу есть.', exHu: 'Enni szeretnék.' },
  { ru: 'пить', hu: 'inni', level: 'A1', pos: 'ige', ex: 'Я пью воду.', exHu: 'Vizet iszom.' },
  { ru: 'один', hu: 'egy', level: 'A1', pos: 'számnév', ex: 'Один билет.', exHu: 'Egy jegy.' },
  { ru: 'два', hu: 'kettő', level: 'A1', pos: 'számnév', ex: 'Два кофе.', exHu: 'Két kávé.' },
  { ru: 'три', hu: 'három', level: 'A1', pos: 'számnév', ex: 'Три часа.', exHu: 'Három óra.' },
  { ru: 'сегодня', hu: 'ma', level: 'A1', pos: 'határozószó', ex: 'Сегодня понедельник.', exHu: 'Ma hétfő van.' },
  { ru: 'завтра', hu: 'holnap', level: 'A1', pos: 'határozószó', ex: 'До завтра!', exHu: 'Holnapig!' },

  // ── A2 ──────────────────────────────────────────────────────────────────
  { ru: 'семья', hu: 'család', level: 'A2', pos: 'főnév', ex: 'Большая семья.', exHu: 'Nagy család.' },
  { ru: 'ребёнок', hu: 'gyerek', level: 'A2', pos: 'főnév', ex: 'Маленький ребёнок.', exHu: 'Kisgyerek.' },
  { ru: 'жена', hu: 'feleség', level: 'A2', pos: 'főnév', ex: 'Моя жена учитель.', exHu: 'A feleségem tanár.' },
  { ru: 'муж', hu: 'férj', level: 'A2', pos: 'főnév', ex: 'Её муж инженер.', exHu: 'A férje mérnök.' },
  { ru: 'деньги', hu: 'pénz', level: 'A2', pos: 'főnév', ex: 'У меня нет денег.', exHu: 'Nincs pénzem.' },
  { ru: 'магазин', hu: 'bolt', level: 'A2', pos: 'főnév', ex: 'Иду в магазин.', exHu: 'Megyek a boltba.' },
  { ru: 'еда', hu: 'étel', level: 'A2', pos: 'főnév', ex: 'Вкусная еда.', exHu: 'Finom étel.' },
  { ru: 'ужин', hu: 'vacsora', level: 'A2', pos: 'főnév', ex: 'Ужин готов.', exHu: 'Kész a vacsora.' },
  { ru: 'машина', hu: 'autó', level: 'A2', pos: 'főnév', ex: 'Новая машина.', exHu: 'Új autó.' },
  { ru: 'поезд', hu: 'vonat', level: 'A2', pos: 'főnév', ex: 'Поезд опаздывает.', exHu: 'A vonat késik.' },
  { ru: 'самолёт', hu: 'repülőgép', level: 'A2', pos: 'főnév', ex: 'Самолёт в Москву.', exHu: 'Repülő Moszkvába.' },
  { ru: 'билет', hu: 'jegy', level: 'A2', pos: 'főnév', ex: 'Два билета, пожалуйста.', exHu: 'Két jegyet kérek.' },
  { ru: 'погода', hu: 'időjárás', level: 'A2', pos: 'főnév', ex: 'Хорошая погода.', exHu: 'Jó idő van.' },
  { ru: 'зима', hu: 'tél', level: 'A2', pos: 'főnév', ex: 'Холодная зима.', exHu: 'Hideg tél.' },
  { ru: 'лето', hu: 'nyár', level: 'A2', pos: 'főnév', ex: 'Жаркое лето.', exHu: 'Forró nyár.' },
  { ru: 'вопрос', hu: 'kérdés', level: 'A2', pos: 'főnév', ex: 'Хороший вопрос.', exHu: 'Jó kérdés.' },
  { ru: 'ответ', hu: 'válasz', level: 'A2', pos: 'főnév', ex: 'Правильный ответ.', exHu: 'Helyes válasz.' },
  { ru: 'слово', hu: 'szó', level: 'A2', pos: 'főnév', ex: 'Новое слово.', exHu: 'Új szó.' },
  { ru: 'работать', hu: 'dolgozni', level: 'A2', pos: 'ige', ex: 'Я работаю в офисе.', exHu: 'Irodában dolgozom.' },
  { ru: 'учиться', hu: 'tanulni', level: 'A2', pos: 'ige', ex: 'Я учусь в университете.', exHu: 'Egyetemen tanulok.' },
  { ru: 'понимать', hu: 'érteni', level: 'A2', pos: 'ige', ex: 'Я понимаю.', exHu: 'Értem.' },
  { ru: 'помнить', hu: 'emlékezni', level: 'A2', pos: 'ige', ex: 'Я не помню.', exHu: 'Nem emlékszem.' },
  { ru: 'видеть', hu: 'látni', level: 'A2', pos: 'ige', ex: 'Я вижу море.', exHu: 'Látom a tengert.' },
  { ru: 'слышать', hu: 'hallani', level: 'A2', pos: 'ige', ex: 'Ты слышишь меня?', exHu: 'Hallasz engem?' },
  { ru: 'ждать', hu: 'várni', level: 'A2', pos: 'ige', ex: 'Я жду автобус.', exHu: 'A buszra várok.' },
  { ru: 'давать', hu: 'adni', level: 'A2', pos: 'ige', ex: 'Дай мне ручку.', exHu: 'Adj egy tollat.' },
  { ru: 'покупать', hu: 'venni / vásárolni', level: 'A2', pos: 'ige', ex: 'Я покупаю хлеб.', exHu: 'Kenyeret veszek.' },
  { ru: 'открывать', hu: 'kinyitni', level: 'A2', pos: 'ige', ex: 'Магазин открывается в восемь.', exHu: 'A bolt nyolckor nyit.' },
  { ru: 'помогать', hu: 'segíteni', level: 'A2', pos: 'ige', ex: 'Помоги мне, пожалуйста.', exHu: 'Segíts, kérlek.' },
  { ru: 'спрашивать', hu: 'kérdezni', level: 'A2', pos: 'ige', ex: 'Он спрашивает дорогу.', exHu: 'Az utat kérdezi.' },
  { ru: 'отвечать', hu: 'válaszolni', level: 'A2', pos: 'ige', ex: 'Отвечай на вопрос.', exHu: 'Válaszolj a kérdésre.' },
  { ru: 'красивый', hu: 'szép', level: 'A2', pos: 'melléknév', ex: 'Красивый город.', exHu: 'Szép város.' },
  { ru: 'трудный', hu: 'nehéz (feladat)', level: 'A2', pos: 'melléknév', ex: 'Трудный вопрос.', exHu: 'Nehéz kérdés.' },
  { ru: 'лёгкий', hu: 'könnyű', level: 'A2', pos: 'melléknév', ex: 'Лёгкий текст.', exHu: 'Könnyű szöveg.' },
  { ru: 'быстрый', hu: 'gyors', level: 'A2', pos: 'melléknév', ex: 'Быстрый поезд.', exHu: 'Gyors vonat.' },
  { ru: 'медленный', hu: 'lassú', level: 'A2', pos: 'melléknév', ex: 'Медленный интернет.', exHu: 'Lassú internet.' },
  { ru: 'важный', hu: 'fontos', level: 'A2', pos: 'melléknév', ex: 'Важный день.', exHu: 'Fontos nap.' },
  { ru: 'интересный', hu: 'érdekes', level: 'A2', pos: 'melléknév', ex: 'Интересный фильм.', exHu: 'Érdekes film.' },
  { ru: 'дорогой', hu: 'drága', level: 'A2', pos: 'melléknév', ex: 'Дорогой ресторан.', exHu: 'Drága étterem.' },
  { ru: 'дешёвый', hu: 'olcsó', level: 'A2', pos: 'melléknév', ex: 'Дешёвый билет.', exHu: 'Olcsó jegy.' },
  { ru: 'сейчас', hu: 'most', level: 'A2', pos: 'határozószó', ex: 'Я занят сейчас.', exHu: 'Most elfoglalt vagyok.' },
  { ru: 'потом', hu: 'aztán / később', level: 'A2', pos: 'határozószó', ex: 'Поговорим потом.', exHu: 'Később beszélünk.' },
  { ru: 'всегда', hu: 'mindig', level: 'A2', pos: 'határozószó', ex: 'Он всегда опаздывает.', exHu: 'Mindig késik.' },
  { ru: 'никогда', hu: 'soha', level: 'A2', pos: 'határozószó', ex: 'Я никогда не был там.', exHu: 'Soha nem voltam ott.' },
  { ru: 'часто', hu: 'gyakran', level: 'A2', pos: 'határozószó', ex: 'Я часто читаю.', exHu: 'Gyakran olvasok.' },
  { ru: 'редко', hu: 'ritkán', level: 'A2', pos: 'határozószó', ex: 'Мы редко видимся.', exHu: 'Ritkán találkozunk.' },
  { ru: 'здесь', hu: 'itt', level: 'A2', pos: 'határozószó', ex: 'Подожди здесь.', exHu: 'Várj itt.' },
  { ru: 'там', hu: 'ott', level: 'A2', pos: 'határozószó', ex: 'Он там.', exHu: 'Ott van.' },

  // ── B1 ──────────────────────────────────────────────────────────────────
  { ru: 'общество', hu: 'társadalom', level: 'B1', pos: 'főnév', ex: 'Современное общество.', exHu: 'A modern társadalom.' },
  { ru: 'правительство', hu: 'kormány', level: 'B1', pos: 'főnév', ex: 'Новое правительство.', exHu: 'Új kormány.' },
  { ru: 'здоровье', hu: 'egészség', level: 'B1', pos: 'főnév', ex: 'Береги здоровье.', exHu: 'Vigyázz az egészségedre.' },
  { ru: 'болезнь', hu: 'betegség', level: 'B1', pos: 'főnév', ex: 'Серьёзная болезнь.', exHu: 'Súlyos betegség.' },
  { ru: 'образование', hu: 'oktatás', level: 'B1', pos: 'főnév', ex: 'Высшее образование.', exHu: 'Felsőoktatás.' },
  { ru: 'опыт', hu: 'tapasztalat', level: 'B1', pos: 'főnév', ex: 'Большой опыт.', exHu: 'Nagy tapasztalat.' },
  { ru: 'решение', hu: 'döntés / megoldás', level: 'B1', pos: 'főnév', ex: 'Трудное решение.', exHu: 'Nehéz döntés.' },
  { ru: 'проблема', hu: 'probléma', level: 'B1', pos: 'főnév', ex: 'Серьёзная проблема.', exHu: 'Komoly probléma.' },
  { ru: 'причина', hu: 'ok', level: 'B1', pos: 'főnév', ex: 'В чём причина?', exHu: 'Mi az ok?' },
  { ru: 'цель', hu: 'cél', level: 'B1', pos: 'főnév', ex: 'Наша главная цель.', exHu: 'A fő célunk.' },
  { ru: 'возможность', hu: 'lehetőség', level: 'B1', pos: 'főnév', ex: 'Хорошая возможность.', exHu: 'Jó lehetőség.' },
  { ru: 'развитие', hu: 'fejlődés', level: 'B1', pos: 'főnév', ex: 'Быстрое развитие.', exHu: 'Gyors fejlődés.' },
  { ru: 'природа', hu: 'természet', level: 'B1', pos: 'főnév', ex: 'Красивая природа.', exHu: 'Gyönyörű természet.' },
  { ru: 'искусство', hu: 'művészet', level: 'B1', pos: 'főnév', ex: 'Современное искусство.', exHu: 'Modern művészet.' },
  { ru: 'наука', hu: 'tudomány', level: 'B1', pos: 'főnév', ex: 'Наука и техника.', exHu: 'Tudomány és technika.' },
  { ru: 'закон', hu: 'törvény', level: 'B1', pos: 'főnév', ex: 'Новый закон.', exHu: 'Új törvény.' },
  { ru: 'изменять', hu: 'megváltoztatni', level: 'B1', pos: 'ige', ex: 'Трудно изменить привычки.', exHu: 'Nehéz megváltoztatni a szokásokat.' },
  { ru: 'развивать', hu: 'fejleszteni', level: 'B1', pos: 'ige', ex: 'Развивать навыки.', exHu: 'Készségeket fejleszteni.' },
  { ru: 'создавать', hu: 'létrehozni', level: 'B1', pos: 'ige', ex: 'Создавать проекты.', exHu: 'Projekteket létrehozni.' },
  { ru: 'решать', hu: 'megoldani / dönteni', level: 'B1', pos: 'ige', ex: 'Решать проблемы.', exHu: 'Problémákat megoldani.' },
  { ru: 'предлагать', hu: 'javasolni', level: 'B1', pos: 'ige', ex: 'Я предлагаю встретиться.', exHu: 'Javaslom, hogy találkozzunk.' },
  { ru: 'получать', hu: 'kapni', level: 'B1', pos: 'ige', ex: 'Получать зарплату.', exHu: 'Fizetést kapni.' },
  { ru: 'использовать', hu: 'használni', level: 'B1', pos: 'ige', ex: 'Использовать компьютер.', exHu: 'Számítógépet használni.' },
  { ru: 'считать', hu: 'gondolni / számolni', level: 'B1', pos: 'ige', ex: 'Я считаю, что он прав.', exHu: 'Úgy gondolom, igaza van.' },
  { ru: 'объяснять', hu: 'megmagyarázni', level: 'B1', pos: 'ige', ex: 'Объясни правило.', exHu: 'Magyarázd el a szabályt.' },
  { ru: 'происходить', hu: 'történni', level: 'B1', pos: 'ige', ex: 'Что происходит?', exHu: 'Mi történik?' },
  { ru: 'зависеть', hu: 'függeni', level: 'B1', pos: 'ige', ex: 'Это зависит от тебя.', exHu: 'Ez tőled függ.' },
  { ru: 'современный', hu: 'modern / mai', level: 'B1', pos: 'melléknév', ex: 'Современная музыка.', exHu: 'Mai zene.' },
  { ru: 'возможный', hu: 'lehetséges', level: 'B1', pos: 'melléknév', ex: 'Это возможно.', exHu: 'Ez lehetséges.' },
  { ru: 'необходимый', hu: 'szükséges', level: 'B1', pos: 'melléknév', ex: 'Необходимый шаг.', exHu: 'Szükséges lépés.' },
  { ru: 'известный', hu: 'ismert / híres', level: 'B1', pos: 'melléknév', ex: 'Известный писатель.', exHu: 'Ismert író.' },
  { ru: 'разный', hu: 'különböző', level: 'B1', pos: 'melléknév', ex: 'Разные мнения.', exHu: 'Különböző vélemények.' },
  { ru: 'обычно', hu: 'általában', level: 'B1', pos: 'határozószó', ex: 'Обычно я встаю рано.', exHu: 'Általában korán kelek.' },
  { ru: 'например', hu: 'például', level: 'B1', pos: 'határozószó', ex: 'Например, вода.', exHu: 'Például a víz.' },
  { ru: 'поэтому', hu: 'ezért', level: 'B1', pos: 'kötőszó', ex: 'Идёт дождь, поэтому я дома.', exHu: 'Esik, ezért otthon vagyok.' },
  { ru: 'хотя', hu: 'bár / habár', level: 'B1', pos: 'kötőszó', ex: 'Хотя было поздно, он пришёл.', exHu: 'Bár késő volt, eljött.' },
  { ru: 'кажется', hu: 'úgy tűnik', level: 'B1', pos: 'kifejezés', ex: 'Кажется, идёт дождь.', exHu: 'Úgy tűnik, esik.' },

  // ── B2 ──────────────────────────────────────────────────────────────────
  { ru: 'впечатление', hu: 'benyomás', level: 'B2', pos: 'főnév', ex: 'Хорошее впечатление.', exHu: 'Jó benyomás.' },
  { ru: 'преимущество', hu: 'előny', level: 'B2', pos: 'főnév', ex: 'Большое преимущество.', exHu: 'Nagy előny.' },
  { ru: 'недостаток', hu: 'hátrány / hiányosság', level: 'B2', pos: 'főnév', ex: 'Главный недостаток.', exHu: 'A fő hátrány.' },
  { ru: 'отношение', hu: 'viszony / kapcsolat', level: 'B2', pos: 'főnév', ex: 'Хорошие отношения.', exHu: 'Jó kapcsolat.' },
  { ru: 'ответственность', hu: 'felelősség', level: 'B2', pos: 'főnév', ex: 'Большая ответственность.', exHu: 'Nagy felelősség.' },
  { ru: 'внимание', hu: 'figyelem', level: 'B2', pos: 'főnév', ex: 'Обрати внимание.', exHu: 'Figyelj oda.' },
  { ru: 'уровень', hu: 'szint', level: 'B2', pos: 'főnév', ex: 'Высокий уровень.', exHu: 'Magas szint.' },
  { ru: 'состояние', hu: 'állapot', level: 'B2', pos: 'főnév', ex: 'Плохое состояние.', exHu: 'Rossz állapot.' },
  { ru: 'событие', hu: 'esemény', level: 'B2', pos: 'főnév', ex: 'Важное событие.', exHu: 'Fontos esemény.' },
  { ru: 'значение', hu: 'jelentés / jelentőség', level: 'B2', pos: 'főnév', ex: 'Большое значение.', exHu: 'Nagy jelentőség.' },
  { ru: 'достигать', hu: 'elérni', level: 'B2', pos: 'ige', ex: 'Достигать цели.', exHu: 'Elérni a célt.' },
  { ru: 'обеспечивать', hu: 'biztosítani', level: 'B2', pos: 'ige', ex: 'Обеспечивать безопасность.', exHu: 'Biztosítani a biztonságot.' },
  { ru: 'требовать', hu: 'követelni / igényelni', level: 'B2', pos: 'ige', ex: 'Это требует времени.', exHu: 'Ez időt igényel.' },
  { ru: 'предпочитать', hu: 'előnyben részesíteni', level: 'B2', pos: 'ige', ex: 'Я предпочитаю чай.', exHu: 'A teát részesítem előnyben.' },
  { ru: 'учитывать', hu: 'figyelembe venni', level: 'B2', pos: 'ige', ex: 'Учитывать все факторы.', exHu: 'Minden tényezőt figyelembe venni.' },
  { ru: 'оценивать', hu: 'értékelni / felmérni', level: 'B2', pos: 'ige', ex: 'Оценивать ситуацию.', exHu: 'Felmérni a helyzetet.' },
  { ru: 'признавать', hu: 'elismerni', level: 'B2', pos: 'ige', ex: 'Признавать ошибку.', exHu: 'Beismerni a hibát.' },
  { ru: 'стремиться', hu: 'törekedni', level: 'B2', pos: 'ige', ex: 'Стремиться к успеху.', exHu: 'A sikerre törekedni.' },
  { ru: 'сомневаться', hu: 'kételkedni', level: 'B2', pos: 'ige', ex: 'Я сомневаюсь в этом.', exHu: 'Kételkedem ebben.' },
  { ru: 'значительный', hu: 'jelentős', level: 'B2', pos: 'melléknév', ex: 'Значительный успех.', exHu: 'Jelentős siker.' },
  { ru: 'подобный', hu: 'hasonló', level: 'B2', pos: 'melléknév', ex: 'Подобный случай.', exHu: 'Hasonló eset.' },
  { ru: 'очевидный', hu: 'nyilvánvaló', level: 'B2', pos: 'melléknév', ex: 'Очевидный ответ.', exHu: 'Nyilvánvaló válasz.' },
  { ru: 'достаточный', hu: 'elegendő', level: 'B2', pos: 'melléknév', ex: 'Достаточный опыт.', exHu: 'Elegendő tapasztalat.' },
  { ru: 'сложный', hu: 'bonyolult', level: 'B2', pos: 'melléknév', ex: 'Сложный вопрос.', exHu: 'Bonyolult kérdés.' },
  { ru: 'напротив', hu: 'ellenkezőleg / szemben', level: 'B2', pos: 'határozószó', ex: 'Напротив, я согласен.', exHu: 'Ellenkezőleg, egyetértek.' },
  { ru: 'вероятно', hu: 'valószínűleg', level: 'B2', pos: 'határozószó', ex: 'Вероятно, он прав.', exHu: 'Valószínűleg igaza van.' },
  { ru: 'кроме того', hu: 'ráadásul', level: 'B2', pos: 'kifejezés', ex: 'Кроме того, это дёшево.', exHu: 'Ráadásul olcsó.' },
  { ru: 'несмотря на', hu: 'ellenére', level: 'B2', pos: 'kifejezés', ex: 'Несмотря на дождь, мы гуляли.', exHu: 'Az eső ellenére sétáltunk.' },

  // ── C1 ──────────────────────────────────────────────────────────────────
  { ru: 'закономерность', hu: 'törvényszerűség', level: 'C1', pos: 'főnév', ex: 'Определённая закономерность.', exHu: 'Bizonyos törvényszerűség.' },
  { ru: 'противоречие', hu: 'ellentmondás', level: 'C1', pos: 'főnév', ex: 'Явное противоречие.', exHu: 'Nyilvánvaló ellentmondás.' },
  { ru: 'обстоятельство', hu: 'körülmény', level: 'C1', pos: 'főnév', ex: 'При любых обстоятельствах.', exHu: 'Bármilyen körülmények között.' },
  { ru: 'преодоление', hu: 'leküzdés', level: 'C1', pos: 'főnév', ex: 'Преодоление трудностей.', exHu: 'A nehézségek leküzdése.' },
  { ru: 'восприятие', hu: 'észlelés / felfogás', level: 'C1', pos: 'főnév', ex: 'Восприятие мира.', exHu: 'A világ felfogása.' },
  { ru: 'подход', hu: 'megközelítés', level: 'C1', pos: 'főnév', ex: 'Новый подход.', exHu: 'Új megközelítés.' },
  { ru: 'сущность', hu: 'lényeg', level: 'C1', pos: 'főnév', ex: 'Сущность проблемы.', exHu: 'A probléma lényege.' },
  { ru: 'осуществлять', hu: 'megvalósítani', level: 'C1', pos: 'ige', ex: 'Осуществлять план.', exHu: 'Megvalósítani a tervet.' },
  { ru: 'подчёркивать', hu: 'hangsúlyozni', level: 'C1', pos: 'ige', ex: 'Подчёркивать важность.', exHu: 'Hangsúlyozni a fontosságot.' },
  { ru: 'предполагать', hu: 'feltételezni', level: 'C1', pos: 'ige', ex: 'Можно предположить, что...', exHu: 'Feltételezhető, hogy...' },
  { ru: 'соответствовать', hu: 'megfelelni', level: 'C1', pos: 'ige', ex: 'Соответствовать требованиям.', exHu: 'Megfelelni a követelményeknek.' },
  { ru: 'опровергать', hu: 'megcáfolni', level: 'C1', pos: 'ige', ex: 'Опровергать теорию.', exHu: 'Megcáfolni az elméletet.' },
  { ru: 'способствовать', hu: 'elősegíteni', level: 'C1', pos: 'ige', ex: 'Способствовать развитию.', exHu: 'Elősegíteni a fejlődést.' },
  { ru: 'воспринимать', hu: 'felfogni / érzékelni', level: 'C1', pos: 'ige', ex: 'Воспринимать критику.', exHu: 'Fogadni a kritikát.' },
  { ru: 'существенный', hu: 'lényeges', level: 'C1', pos: 'melléknév', ex: 'Существенная разница.', exHu: 'Lényeges különbség.' },
  { ru: 'неизбежный', hu: 'elkerülhetetlen', level: 'C1', pos: 'melléknév', ex: 'Неизбежный результат.', exHu: 'Elkerülhetetlen eredmény.' },
  { ru: 'противоречивый', hu: 'ellentmondásos', level: 'C1', pos: 'melléknév', ex: 'Противоречивые данные.', exHu: 'Ellentmondásos adatok.' },
  { ru: 'целесообразный', hu: 'célszerű', level: 'C1', pos: 'melléknév', ex: 'Целесообразное решение.', exHu: 'Célszerű döntés.' },
  { ru: 'тем не менее', hu: 'mindazonáltal', level: 'C1', pos: 'kifejezés', ex: 'Тем не менее, я согласен.', exHu: 'Mindazonáltal egyetértek.' },
  { ru: 'вследствие', hu: 'következtében', level: 'C1', pos: 'elöljárószó', ex: 'Вследствие ошибки.', exHu: 'Egy hiba következtében.' },

  // ── C2 ──────────────────────────────────────────────────────────────────
  { ru: 'многогранность', hu: 'sokrétűség', level: 'C2', pos: 'főnév', ex: 'Многогранность таланта.', exHu: 'A tehetség sokrétűsége.' },
  { ru: 'самобытность', hu: 'egyediség / eredetiség', level: 'C2', pos: 'főnév', ex: 'Культурная самобытность.', exHu: 'Kulturális eredetiség.' },
  { ru: 'проницательность', hu: 'éleslátás', level: 'C2', pos: 'főnév', ex: 'Редкая проницательность.', exHu: 'Ritka éleslátás.' },
  { ru: 'изощрённость', hu: 'kifinomultság', level: 'C2', pos: 'főnév', ex: 'Изощрённость стиля.', exHu: 'A stílus kifinomultsága.' },
  { ru: 'беспристрастность', hu: 'pártatlanság', level: 'C2', pos: 'főnév', ex: 'Полная беспристрастность.', exHu: 'Teljes pártatlanság.' },
  { ru: 'подоплёка', hu: 'háttér / rejtett ok', level: 'C2', pos: 'főnév', ex: 'Скрытая подоплёка.', exHu: 'Rejtett háttér.' },
  { ru: 'усугублять', hu: 'súlyosbítani', level: 'C2', pos: 'ige', ex: 'Усугублять положение.', exHu: 'Súlyosbítani a helyzetet.' },
  { ru: 'изобиловать', hu: 'bővelkedni', level: 'C2', pos: 'ige', ex: 'Текст изобилует ошибками.', exHu: 'A szöveg hemzseg a hibáktól.' },
  { ru: 'сподвигнуть', hu: 'ösztönözni (tettre)', level: 'C2', pos: 'ige', ex: 'Это сподвигло его на перемены.', exHu: 'Ez változásra ösztönözte.' },
  { ru: 'нивелировать', hu: 'kiegyenlíteni / semlegesíteni', level: 'C2', pos: 'ige', ex: 'Нивелировать различия.', exHu: 'Kiegyenlíteni a különbségeket.' },
  { ru: 'скрупулёзный', hu: 'aprólékos / precíz', level: 'C2', pos: 'melléknév', ex: 'Скрупулёзный анализ.', exHu: 'Aprólékos elemzés.' },
  { ru: 'изощрённый', hu: 'kifinomult / agyafúrt', level: 'C2', pos: 'melléknév', ex: 'Изощрённый план.', exHu: 'Agyafúrt terv.' },
  { ru: 'опрометчивый', hu: 'meggondolatlan', level: 'C2', pos: 'melléknév', ex: 'Опрометчивое решение.', exHu: 'Meggondolatlan döntés.' },
  { ru: 'самодостаточный', hu: 'önellátó / önmagában elég', level: 'C2', pos: 'melléknév', ex: 'Самодостаточный человек.', exHu: 'Önmagában elégedett ember.' },
  { ru: 'зачастую', hu: 'gyakorta', level: 'C2', pos: 'határozószó', ex: 'Зачастую это так.', exHu: 'Gyakorta így van.' },
  { ru: 'впредь', hu: 'ezentúl', level: 'C2', pos: 'határozószó', ex: 'Впредь будь осторожен.', exHu: 'Ezentúl légy óvatos.' },

  // ===== Bővítés: több szó minden szinten, C2-ig =====
  // -- Étel --
  { ru: 'сыр', hu: 'sajt', level: 'A1', pos: 'főnév', ex: 'Кусок сыра.', exHu: 'Egy szelet sajt.' },
  { ru: 'мясо', hu: 'hús', level: 'A1', pos: 'főnév', ex: 'Жареное мясо.', exHu: 'Sült hús.' },
  { ru: 'рыба', hu: 'hal', level: 'A1', pos: 'főnév', ex: 'Свежая рыба.', exHu: 'Friss hal.' },
  { ru: 'суп', hu: 'leves', level: 'A1', pos: 'főnév', ex: 'Горячий суп.', exHu: 'Forró leves.' },
  { ru: 'рис', hu: 'rizs', level: 'A1', pos: 'főnév', ex: 'Рис с овощами.', exHu: 'Rizs zöldséggel.' },
  { ru: 'соль', hu: 'só', level: 'A1', pos: 'főnév', ex: 'Соль и перец.', exHu: 'Só és bors.' },
  { ru: 'сахар', hu: 'cukor', level: 'A1', pos: 'főnév', ex: 'Чай без сахара.', exHu: 'Tea cukor nélkül.' },
  { ru: 'масло', hu: 'vaj / olaj', level: 'A2', pos: 'főnév', ex: 'Хлеб с маслом.', exHu: 'Vajas kenyér.' },
  { ru: 'яйцо', hu: 'tojás', level: 'A1', pos: 'főnév', ex: 'Варёное яйцо.', exHu: 'Főtt tojás.' },
  { ru: 'курица', hu: 'csirke', level: 'A2', pos: 'főnév', ex: 'Курица с рисом.', exHu: 'Csirke rizzsel.' },
  { ru: 'колбаса', hu: 'kolbász', level: 'B1', pos: 'főnév', ex: 'Бутерброд с колбасой.', exHu: 'Kolbászos szendvics.' },
  { ru: 'мёд', hu: 'méz', level: 'B1', pos: 'főnév', ex: 'Чай с мёдом.', exHu: 'Tea mézzel.' },
  { ru: 'торт', hu: 'torta', level: 'A2', pos: 'főnév', ex: 'Шоколадный торт.', exHu: 'Csokitorta.' },
  { ru: 'печенье', hu: 'keksz', level: 'A2', pos: 'főnév', ex: 'Печенье к чаю.', exHu: 'Keksz a teához.' },
  { ru: 'мороженое', hu: 'fagylalt', level: 'A2', pos: 'főnév', ex: 'Ванильное мороженое.', exHu: 'Vaníliafagyi.' },
  { ru: 'орех', hu: 'dió / mogyoró', level: 'B1', pos: 'főnév', ex: 'Грецкий орех.', exHu: 'Dió.' },
  { ru: 'каша', hu: 'kása', level: 'A2', pos: 'főnév', ex: 'Овсяная каша.', exHu: 'Zabkása.' },
  // -- Gyümölcs --
  { ru: 'яблоко', hu: 'alma', level: 'A1', pos: 'főnév', ex: 'Красное яблоко.', exHu: 'Piros alma.' },
  { ru: 'банан', hu: 'banán', level: 'A1', pos: 'főnév', ex: 'Спелый банан.', exHu: 'Érett banán.' },
  { ru: 'апельсин', hu: 'narancs', level: 'A2', pos: 'főnév', ex: 'Сок из апельсина.', exHu: 'Narancslé.' },
  { ru: 'груша', hu: 'körte', level: 'A2', pos: 'főnév', ex: 'Сладкая груша.', exHu: 'Édes körte.' },
  { ru: 'виноград', hu: 'szőlő', level: 'A2', pos: 'főnév', ex: 'Зелёный виноград.', exHu: 'Zöld szőlő.' },
  { ru: 'клубника', hu: 'eper', level: 'B1', pos: 'főnév', ex: 'Клубника со сливками.', exHu: 'Eper tejszínnel.' },
  { ru: 'лимон', hu: 'citrom', level: 'A2', pos: 'főnév', ex: 'Кислый лимон.', exHu: 'Savanyú citrom.' },
  { ru: 'вишня', hu: 'cseresznye', level: 'B1', pos: 'főnév', ex: 'Спелая вишня.', exHu: 'Érett cseresznye.' },
  { ru: 'арбуз', hu: 'görögdinnye', level: 'B1', pos: 'főnév', ex: 'Сладкий арбуз.', exHu: 'Édes görögdinnye.' },
  { ru: 'персик', hu: 'őszibarack', level: 'B1', pos: 'főnév', ex: 'Сочный персик.', exHu: 'Lédús őszibarack.' },
  { ru: 'слива', hu: 'szilva', level: 'B1', pos: 'főnév', ex: 'Синяя слива.', exHu: 'Kék szilva.' },
  { ru: 'малина', hu: 'málna', level: 'B1', pos: 'főnév', ex: 'Варенье из малины.', exHu: 'Málnalekvár.' },
  // -- Zöldség --
  { ru: 'помидор', hu: 'paradicsom', level: 'A2', pos: 'főnév', ex: 'Красный помидор.', exHu: 'Piros paradicsom.' },
  { ru: 'картофель', hu: 'burgonya', level: 'A2', pos: 'főnév', ex: 'Варёный картофель.', exHu: 'Főtt burgonya.' },
  { ru: 'огурец', hu: 'uborka', level: 'A2', pos: 'főnév', ex: 'Свежий огурец.', exHu: 'Friss uborka.' },
  { ru: 'лук', hu: 'hagyma', level: 'A2', pos: 'főnév', ex: 'Зелёный лук.', exHu: 'Zöldhagyma.' },
  { ru: 'морковь', hu: 'sárgarépa', level: 'A2', pos: 'főnév', ex: 'Тёртая морковь.', exHu: 'Reszelt répa.' },
  { ru: 'капуста', hu: 'káposzta', level: 'B1', pos: 'főnév', ex: 'Салат из капусты.', exHu: 'Káposztasaláta.' },
  { ru: 'чеснок', hu: 'fokhagyma', level: 'B1', pos: 'főnév', ex: 'Зубчик чеснока.', exHu: 'Egy gerezd fokhagyma.' },
  { ru: 'грибы', hu: 'gomba', level: 'B1', pos: 'főnév', ex: 'Суп с грибами.', exHu: 'Gombaleves.' },
  { ru: 'перец', hu: 'bors / paprika', level: 'A2', pos: 'főnév', ex: 'Красный перец.', exHu: 'Piros paprika.' },
  // -- Italok --
  { ru: 'сок', hu: 'gyümölcslé', level: 'A1', pos: 'főnév', ex: 'Яблочный сок.', exHu: 'Almalé.' },
  { ru: 'пиво', hu: 'sör', level: 'A2', pos: 'főnév', ex: 'Холодное пиво.', exHu: 'Hideg sör.' },
  { ru: 'вино', hu: 'bor', level: 'A2', pos: 'főnév', ex: 'Красное вино.', exHu: 'Vörösbor.' },
  { ru: 'лимонад', hu: 'limonádé', level: 'A2', pos: 'főnév', ex: 'Стакан лимонада.', exHu: 'Egy pohár limonádé.' },
  { ru: 'квас', hu: 'kvász', level: 'B1', pos: 'főnév', ex: 'Холодный квас.', exHu: 'Hideg kvász.' },
  // -- Állatok --
  { ru: 'кот', hu: 'macska', level: 'A1', pos: 'főnév', ex: 'Чёрный кот.', exHu: 'Fekete macska.' },
  { ru: 'собака', hu: 'kutya', level: 'A1', pos: 'főnév', ex: 'Большая собака.', exHu: 'Nagy kutya.' },
  { ru: 'лошадь', hu: 'ló', level: 'A1', pos: 'főnév', ex: 'Белая лошадь.', exHu: 'Fehér ló.' },
  { ru: 'корова', hu: 'tehén', level: 'A1', pos: 'főnév', ex: 'Корова даёт молоко.', exHu: 'A tehén tejet ad.' },
  { ru: 'свинья', hu: 'disznó', level: 'A2', pos: 'főnév', ex: 'Розовая свинья.', exHu: 'Rózsaszín disznó.' },
  { ru: 'медведь', hu: 'medve', level: 'A2', pos: 'főnév', ex: 'Бурый медведь.', exHu: 'Barnamedve.' },
  { ru: 'волк', hu: 'farkas', level: 'B1', pos: 'főnév', ex: 'Голодный волк.', exHu: 'Éhes farkas.' },
  { ru: 'лиса', hu: 'róka', level: 'B1', pos: 'főnév', ex: 'Хитрая лиса.', exHu: 'Ravasz róka.' },
  { ru: 'заяц', hu: 'nyúl', level: 'A2', pos: 'főnév', ex: 'Быстрый заяц.', exHu: 'Gyors nyúl.' },
  { ru: 'лев', hu: 'oroszlán', level: 'A2', pos: 'főnév', ex: 'Лев — царь зверей.', exHu: 'Az oroszlán az állatok királya.' },
  { ru: 'тигр', hu: 'tigris', level: 'A2', pos: 'főnév', ex: 'Полосатый тигр.', exHu: 'Csíkos tigris.' },
  { ru: 'слон', hu: 'elefánt', level: 'A2', pos: 'főnév', ex: 'Большой слон.', exHu: 'Nagy elefánt.' },
  { ru: 'обезьяна', hu: 'majom', level: 'A2', pos: 'főnév', ex: 'Обезьяна на дереве.', exHu: 'Majom a fán.' },
  { ru: 'змея', hu: 'kígyó', level: 'B1', pos: 'főnév', ex: 'Ядовитая змея.', exHu: 'Mérges kígyó.' },
  { ru: 'лягушка', hu: 'béka', level: 'B1', pos: 'főnév', ex: 'Зелёная лягушка.', exHu: 'Zöld béka.' },
  { ru: 'мышь', hu: 'egér', level: 'A2', pos: 'főnév', ex: 'Маленькая мышь.', exHu: 'Kis egér.' },
  // -- Madarak és rovarok --
  { ru: 'птица', hu: 'madár', level: 'A1', pos: 'főnév', ex: 'Птица поёт.', exHu: 'A madár énekel.' },
  { ru: 'орёл', hu: 'sas', level: 'B1', pos: 'főnév', ex: 'Орёл в небе.', exHu: 'Sas az égen.' },
  { ru: 'сова', hu: 'bagoly', level: 'B1', pos: 'főnév', ex: 'Ночная сова.', exHu: 'Éjszakai bagoly.' },
  { ru: 'утка', hu: 'kacsa', level: 'A2', pos: 'főnév', ex: 'Утка на пруду.', exHu: 'Kacsa a tavon.' },
  { ru: 'попугай', hu: 'papagáj', level: 'B1', pos: 'főnév', ex: 'Говорящий попугай.', exHu: 'Beszélő papagáj.' },
  { ru: 'муха', hu: 'légy', level: 'B1', pos: 'főnév', ex: 'Надоедливая муха.', exHu: 'Zavaró légy.' },
  { ru: 'комар', hu: 'szúnyog', level: 'B1', pos: 'főnév', ex: 'Комар кусает.', exHu: 'A szúnyog csíp.' },
  { ru: 'пчела', hu: 'méh', level: 'B1', pos: 'főnév', ex: 'Пчела делает мёд.', exHu: 'A méh mézet készít.' },
  { ru: 'бабочка', hu: 'pillangó', level: 'A2', pos: 'főnév', ex: 'Красивая бабочка.', exHu: 'Szép pillangó.' },
  { ru: 'паук', hu: 'pók', level: 'B1', pos: 'főnév', ex: 'Паук плетёт паутину.', exHu: 'A pók hálót sző.' },
  // -- Tenger --
  { ru: 'море', hu: 'tenger', level: 'A1', pos: 'főnév', ex: 'Синее море.', exHu: 'Kék tenger.' },
  { ru: 'пляж', hu: 'strand', level: 'A2', pos: 'főnév', ex: 'Песчаный пляж.', exHu: 'Homokos strand.' },
  { ru: 'волна', hu: 'hullám', level: 'B1', pos: 'főnév', ex: 'Большая волна.', exHu: 'Nagy hullám.' },
  { ru: 'песок', hu: 'homok', level: 'A2', pos: 'főnév', ex: 'Тёплый песок.', exHu: 'Meleg homok.' },
  { ru: 'акула', hu: 'cápa', level: 'B1', pos: 'főnév', ex: 'Опасная акула.', exHu: 'Veszélyes cápa.' },
  { ru: 'кит', hu: 'bálna', level: 'B1', pos: 'főnév', ex: 'Огромный кит.', exHu: 'Hatalmas bálna.' },
  { ru: 'дельфин', hu: 'delfin', level: 'A2', pos: 'főnév', ex: 'Умный дельфин.', exHu: 'Okos delfin.' },
  { ru: 'остров', hu: 'sziget', level: 'A2', pos: 'főnév', ex: 'Тропический остров.', exHu: 'Trópusi sziget.' },
  { ru: 'корабль', hu: 'hajó', level: 'A2', pos: 'főnév', ex: 'Большой корабль.', exHu: 'Nagy hajó.' },
  { ru: 'лодка', hu: 'csónak', level: 'A2', pos: 'főnév', ex: 'Маленькая лодка.', exHu: 'Kis csónak.' },
  // -- Színek --
  { ru: 'красный', hu: 'piros', level: 'A1', pos: 'melléknév', ex: 'Красный флаг.', exHu: 'Piros zászló.' },
  { ru: 'синий', hu: 'kék', level: 'A1', pos: 'melléknév', ex: 'Синее небо.', exHu: 'Kék ég.' },
  { ru: 'зелёный', hu: 'zöld', level: 'A1', pos: 'melléknév', ex: 'Зелёный лист.', exHu: 'Zöld levél.' },
  { ru: 'жёлтый', hu: 'sárga', level: 'A1', pos: 'melléknév', ex: 'Жёлтое солнце.', exHu: 'Sárga nap.' },
  { ru: 'чёрный', hu: 'fekete', level: 'A1', pos: 'melléknév', ex: 'Чёрный кот.', exHu: 'Fekete macska.' },
  { ru: 'белый', hu: 'fehér', level: 'A1', pos: 'melléknév', ex: 'Белый снег.', exHu: 'Fehér hó.' },
  { ru: 'серый', hu: 'szürke', level: 'A2', pos: 'melléknév', ex: 'Серый день.', exHu: 'Szürke nap.' },
  { ru: 'розовый', hu: 'rózsaszín', level: 'A2', pos: 'melléknév', ex: 'Розовый цветок.', exHu: 'Rózsaszín virág.' },
  { ru: 'коричневый', hu: 'barna', level: 'A2', pos: 'melléknév', ex: 'Коричневый стол.', exHu: 'Barna asztal.' },
  { ru: 'фиолетовый', hu: 'lila', level: 'A2', pos: 'melléknév', ex: 'Фиолетовый шарф.', exHu: 'Lila sál.' },
  { ru: 'голубой', hu: 'világoskék', level: 'A2', pos: 'melléknév', ex: 'Голубая рубашка.', exHu: 'Világoskék ing.' },
  { ru: 'оранжевый', hu: 'narancssárga', level: 'A2', pos: 'melléknév', ex: 'Оранжевый закат.', exHu: 'Narancssárga naplemente.' },
  // -- Test --
  { ru: 'голова', hu: 'fej', level: 'A1', pos: 'főnév', ex: 'Болит голова.', exHu: 'Fáj a fejem.' },
  { ru: 'рука', hu: 'kéz / kar', level: 'A1', pos: 'főnév', ex: 'Правая рука.', exHu: 'Jobb kéz.' },
  { ru: 'нога', hu: 'láb', level: 'A1', pos: 'főnév', ex: 'Левая нога.', exHu: 'Bal láb.' },
  { ru: 'глаз', hu: 'szem', level: 'A1', pos: 'főnév', ex: 'Голубые глаза.', exHu: 'Kék szemek.' },
  { ru: 'ухо', hu: 'fül', level: 'A1', pos: 'főnév', ex: 'Правое ухо.', exHu: 'Jobb fül.' },
  { ru: 'нос', hu: 'orr', level: 'A1', pos: 'főnév', ex: 'Красный нос.', exHu: 'Piros orr.' },
  { ru: 'рот', hu: 'száj', level: 'A1', pos: 'főnév', ex: 'Открой рот.', exHu: 'Nyisd ki a szád.' },
  { ru: 'зуб', hu: 'fog', level: 'A1', pos: 'főnév', ex: 'Белые зубы.', exHu: 'Fehér fogak.' },
  { ru: 'волосы', hu: 'haj', level: 'A1', pos: 'főnév', ex: 'Длинные волосы.', exHu: 'Hosszú haj.' },
  { ru: 'лицо', hu: 'arc', level: 'A1', pos: 'főnév', ex: 'Доброе лицо.', exHu: 'Kedves arc.' },
  { ru: 'сердце', hu: 'szív', level: 'A1', pos: 'főnév', ex: 'Сердце бьётся.', exHu: 'A szív ver.' },
  { ru: 'спина', hu: 'hát', level: 'A2', pos: 'főnév', ex: 'Болит спина.', exHu: 'Fáj a hátam.' },
  { ru: 'палец', hu: 'ujj', level: 'A2', pos: 'főnév', ex: 'Палец на руке.', exHu: 'Ujj a kézen.' },
  { ru: 'кровь', hu: 'vér', level: 'A2', pos: 'főnév', ex: 'Красная кровь.', exHu: 'Piros vér.' },
  { ru: 'кожа', hu: 'bőr', level: 'A2', pos: 'főnév', ex: 'Мягкая кожа.', exHu: 'Puha bőr.' },
  // -- Ruhák --
  { ru: 'одежда', hu: 'ruha (ruházat)', level: 'A2', pos: 'főnév', ex: 'Тёплая одежда.', exHu: 'Meleg ruházat.' },
  { ru: 'рубашка', hu: 'ing', level: 'A2', pos: 'főnév', ex: 'Белая рубашка.', exHu: 'Fehér ing.' },
  { ru: 'платье', hu: 'ruha (női)', level: 'A2', pos: 'főnév', ex: 'Красивое платье.', exHu: 'Szép ruha.' },
  { ru: 'брюки', hu: 'nadrág', level: 'A2', pos: 'főnév', ex: 'Чёрные брюки.', exHu: 'Fekete nadrág.' },
  { ru: 'юбка', hu: 'szoknya', level: 'A2', pos: 'főnév', ex: 'Короткая юбка.', exHu: 'Rövid szoknya.' },
  { ru: 'куртка', hu: 'dzseki / kabát', level: 'A2', pos: 'főnév', ex: 'Тёплая куртка.', exHu: 'Meleg kabát.' },
  { ru: 'пальто', hu: 'kabát (felöltő)', level: 'A2', pos: 'főnév', ex: 'Зимнее пальто.', exHu: 'Téli kabát.' },
  { ru: 'шапка', hu: 'sapka', level: 'A2', pos: 'főnév', ex: 'Тёплая шапка.', exHu: 'Meleg sapka.' },
  { ru: 'обувь', hu: 'lábbeli', level: 'B1', pos: 'főnév', ex: 'Удобная обувь.', exHu: 'Kényelmes lábbeli.' },
  { ru: 'носки', hu: 'zokni', level: 'A2', pos: 'főnév', ex: 'Тёплые носки.', exHu: 'Meleg zokni.' },
  { ru: 'перчатки', hu: 'kesztyű', level: 'B1', pos: 'főnév', ex: 'Кожаные перчатки.', exHu: 'Bőrkesztyű.' },
  { ru: 'сумка', hu: 'táska', level: 'A2', pos: 'főnév', ex: 'Тяжёлая сумка.', exHu: 'Nehéz táska.' },
  { ru: 'очки', hu: 'szemüveg', level: 'A2', pos: 'főnév', ex: 'Солнечные очки.', exHu: 'Napszemüveg.' },
  // -- Ház --
  { ru: 'квартира', hu: 'lakás', level: 'A1', pos: 'főnév', ex: 'Новая квартира.', exHu: 'Új lakás.' },
  { ru: 'комната', hu: 'szoba', level: 'A1', pos: 'főnév', ex: 'Светлая комната.', exHu: 'Világos szoba.' },
  { ru: 'кухня', hu: 'konyha', level: 'A1', pos: 'főnév', ex: 'Большая кухня.', exHu: 'Nagy konyha.' },
  { ru: 'стена', hu: 'fal', level: 'A2', pos: 'főnév', ex: 'Белая стена.', exHu: 'Fehér fal.' },
  { ru: 'пол', hu: 'padló', level: 'A2', pos: 'főnév', ex: 'Чистый пол.', exHu: 'Tiszta padló.' },
  { ru: 'крыша', hu: 'tető', level: 'A2', pos: 'főnév', ex: 'Красная крыша.', exHu: 'Piros tető.' },
  { ru: 'кровать', hu: 'ágy', level: 'A1', pos: 'főnév', ex: 'Мягкая кровать.', exHu: 'Puha ágy.' },
  { ru: 'диван', hu: 'kanapé', level: 'A2', pos: 'főnév', ex: 'Удобный диван.', exHu: 'Kényelmes kanapé.' },
  { ru: 'шкаф', hu: 'szekrény', level: 'A2', pos: 'főnév', ex: 'Большой шкаф.', exHu: 'Nagy szekrény.' },
  { ru: 'зеркало', hu: 'tükör', level: 'A2', pos: 'főnév', ex: 'Круглое зеркало.', exHu: 'Kerek tükör.' },
  { ru: 'лампа', hu: 'lámpa', level: 'A2', pos: 'főnév', ex: 'Настольная лампа.', exHu: 'Asztali lámpa.' },
  { ru: 'ключ', hu: 'kulcs', level: 'A1', pos: 'főnév', ex: 'Ключ от двери.', exHu: 'Az ajtó kulcsa.' },
  { ru: 'лестница', hu: 'lépcső', level: 'B1', pos: 'főnév', ex: 'Крутая лестница.', exHu: 'Meredek lépcső.' },
  { ru: 'мебель', hu: 'bútor', level: 'B1', pos: 'főnév', ex: 'Новая мебель.', exHu: 'Új bútor.' },
  // -- Fürdőszoba --
  { ru: 'душ', hu: 'zuhany', level: 'A2', pos: 'főnév', ex: 'Тёплый душ.', exHu: 'Meleg zuhany.' },
  { ru: 'ванна', hu: 'fürdőkád', level: 'A2', pos: 'főnév', ex: 'Горячая ванна.', exHu: 'Forró fürdő.' },
  { ru: 'туалет', hu: 'WC', level: 'A1', pos: 'főnév', ex: 'Где туалет?', exHu: 'Hol a WC?' },
  { ru: 'полотенце', hu: 'törölköző', level: 'A2', pos: 'főnév', ex: 'Чистое полотенце.', exHu: 'Tiszta törölköző.' },
  { ru: 'мыло', hu: 'szappan', level: 'A2', pos: 'főnév', ex: 'Кусок мыла.', exHu: 'Egy darab szappan.' },
  { ru: 'зубная паста', hu: 'fogkrém', level: 'B1', pos: 'főnév', ex: 'Мятная зубная паста.', exHu: 'Mentás fogkrém.' },
  // -- Város --
  { ru: 'площадь', hu: 'tér', level: 'A2', pos: 'főnév', ex: 'Красная площадь.', exHu: 'Vörös tér.' },
  { ru: 'банк', hu: 'bank', level: 'A1', pos: 'főnév', ex: 'Иду в банк.', exHu: 'Megyek a bankba.' },
  { ru: 'больница', hu: 'kórház', level: 'A2', pos: 'főnév', ex: 'Городская больница.', exHu: 'Városi kórház.' },
  { ru: 'аптека', hu: 'gyógyszertár', level: 'A2', pos: 'főnév', ex: 'Аптека рядом.', exHu: 'A gyógyszertár közel van.' },
  { ru: 'парк', hu: 'park', level: 'A1', pos: 'főnév', ex: 'Гулять в парке.', exHu: 'Sétálni a parkban.' },
  { ru: 'рынок', hu: 'piac', level: 'A2', pos: 'főnév', ex: 'Свежий рынок.', exHu: 'Friss piac.' },
  { ru: 'вокзал', hu: 'pályaudvar', level: 'A2', pos: 'főnév', ex: 'Центральный вокзал.', exHu: 'Központi pályaudvar.' },
  { ru: 'мост', hu: 'híd', level: 'A2', pos: 'főnév', ex: 'Старый мост.', exHu: 'Régi híd.' },
  { ru: 'здание', hu: 'épület', level: 'A2', pos: 'főnév', ex: 'Высокое здание.', exHu: 'Magas épület.' },
  { ru: 'музей', hu: 'múzeum', level: 'A2', pos: 'főnév', ex: 'Художественный музей.', exHu: 'Művészeti múzeum.' },
  { ru: 'театр', hu: 'színház', level: 'A2', pos: 'főnév', ex: 'Идём в театр.', exHu: 'Színházba megyünk.' },
  { ru: 'библиотека', hu: 'könyvtár', level: 'A2', pos: 'főnév', ex: 'Тихая библиотека.', exHu: 'Csendes könyvtár.' },
  { ru: 'церковь', hu: 'templom', level: 'A2', pos: 'főnév', ex: 'Старая церковь.', exHu: 'Régi templom.' },
  // -- Iskola --
  { ru: 'урок', hu: 'óra / lecke', level: 'A1', pos: 'főnév', ex: 'Урок русского.', exHu: 'Orosz óra.' },
  { ru: 'учитель', hu: 'tanár', level: 'A1', pos: 'főnév', ex: 'Строгий учитель.', exHu: 'Szigorú tanár.' },
  { ru: 'ученик', hu: 'tanuló', level: 'A2', pos: 'főnév', ex: 'Хороший ученик.', exHu: 'Jó tanuló.' },
  { ru: 'класс', hu: 'osztály / terem', level: 'A1', pos: 'főnév', ex: 'Пустой класс.', exHu: 'Üres osztályterem.' },
  { ru: 'тетрадь', hu: 'füzet', level: 'A2', pos: 'főnév', ex: 'Новая тетрадь.', exHu: 'Új füzet.' },
  { ru: 'ручка', hu: 'toll', level: 'A1', pos: 'főnév', ex: 'Синяя ручка.', exHu: 'Kék toll.' },
  { ru: 'карандаш', hu: 'ceruza', level: 'A1', pos: 'főnév', ex: 'Простой карандаш.', exHu: 'Egyszerű ceruza.' },
  { ru: 'экзамен', hu: 'vizsga', level: 'A2', pos: 'főnév', ex: 'Сдать экзамен.', exHu: 'Levizsgázni.' },
  { ru: 'оценка', hu: 'osztályzat', level: 'B1', pos: 'főnév', ex: 'Хорошая оценка.', exHu: 'Jó jegy.' },
  { ru: 'университет', hu: 'egyetem', level: 'A2', pos: 'főnév', ex: 'Учиться в университете.', exHu: 'Egyetemen tanulni.' },
  { ru: 'студент', hu: 'egyetemista', level: 'A1', pos: 'főnév', ex: 'Молодой студент.', exHu: 'Fiatal egyetemista.' },
  { ru: 'словарь', hu: 'szótár', level: 'A2', pos: 'főnév', ex: 'Русский словарь.', exHu: 'Orosz szótár.' },
  { ru: 'ошибка', hu: 'hiba', level: 'A2', pos: 'főnév', ex: 'Маленькая ошибка.', exHu: 'Kis hiba.' },
  // -- Munka és foglalkozások --
  { ru: 'офис', hu: 'iroda', level: 'A2', pos: 'főnév', ex: 'Работать в офисе.', exHu: 'Irodában dolgozni.' },
  { ru: 'начальник', hu: 'főnök', level: 'B1', pos: 'főnév', ex: 'Строгий начальник.', exHu: 'Szigorú főnök.' },
  { ru: 'зарплата', hu: 'fizetés', level: 'B1', pos: 'főnév', ex: 'Высокая зарплата.', exHu: 'Magas fizetés.' },
  { ru: 'компания', hu: 'cég', level: 'A2', pos: 'főnév', ex: 'Большая компания.', exHu: 'Nagy cég.' },
  { ru: 'встреча', hu: 'találkozó', level: 'A2', pos: 'főnév', ex: 'Важная встреча.', exHu: 'Fontos találkozó.' },
  { ru: 'договор', hu: 'szerződés', level: 'B1', pos: 'főnév', ex: 'Подписать договор.', exHu: 'Aláírni a szerződést.' },
  { ru: 'врач', hu: 'orvos', level: 'A1', pos: 'főnév', ex: 'Опытный врач.', exHu: 'Tapasztalt orvos.' },
  { ru: 'инженер', hu: 'mérnök', level: 'A2', pos: 'főnév', ex: 'Инженер на заводе.', exHu: 'Mérnök a gyárban.' },
  { ru: 'повар', hu: 'szakács', level: 'A2', pos: 'főnév', ex: 'Хороший повар.', exHu: 'Jó szakács.' },
  { ru: 'официант', hu: 'pincér', level: 'A2', pos: 'főnév', ex: 'Официант принёс меню.', exHu: 'A pincér hozta az étlapot.' },
  { ru: 'продавец', hu: 'eladó', level: 'A2', pos: 'főnév', ex: 'Продавец в магазине.', exHu: 'Eladó a boltban.' },
  { ru: 'водитель', hu: 'sofőr', level: 'A2', pos: 'főnév', ex: 'Водитель автобуса.', exHu: 'Buszsofőr.' },
  { ru: 'полицейский', hu: 'rendőr', level: 'A2', pos: 'főnév', ex: 'Полицейский на улице.', exHu: 'Rendőr az utcán.' },
  { ru: 'художник', hu: 'festő / művész', level: 'A2', pos: 'főnév', ex: 'Известный художник.', exHu: 'Híres festő.' },
  { ru: 'писатель', hu: 'író', level: 'A2', pos: 'főnév', ex: 'Русский писатель.', exHu: 'Orosz író.' },
  { ru: 'программист', hu: 'programozó', level: 'B1', pos: 'főnév', ex: 'Опытный программист.', exHu: 'Tapasztalt programozó.' },
  { ru: 'юрист', hu: 'jogász', level: 'B1', pos: 'főnév', ex: 'Хороший юрист.', exHu: 'Jó jogász.' },
  // -- Közlekedés / utazás --
  { ru: 'путешествие', hu: 'utazás', level: 'A2', pos: 'főnév', ex: 'Долгое путешествие.', exHu: 'Hosszú utazás.' },
  { ru: 'автобус', hu: 'busz', level: 'A1', pos: 'főnév', ex: 'Ждать автобус.', exHu: 'Buszra várni.' },
  { ru: 'метро', hu: 'metró', level: 'A1', pos: 'főnév', ex: 'Ехать на метро.', exHu: 'Metróval menni.' },
  { ru: 'такси', hu: 'taxi', level: 'A1', pos: 'főnév', ex: 'Вызвать такси.', exHu: 'Taxit hívni.' },
  { ru: 'велосипед', hu: 'kerékpár', level: 'A2', pos: 'főnév', ex: 'Кататься на велосипеде.', exHu: 'Biciklizni.' },
  { ru: 'паспорт', hu: 'útlevél', level: 'A2', pos: 'főnév', ex: 'Показать паспорт.', exHu: 'Megmutatni az útlevelet.' },
  { ru: 'чемодан', hu: 'bőrönd', level: 'A2', pos: 'főnév', ex: 'Тяжёлый чемодан.', exHu: 'Nehéz bőrönd.' },
  { ru: 'карта', hu: 'térkép / kártya', level: 'A2', pos: 'főnév', ex: 'Карта города.', exHu: 'A város térképe.' },
  { ru: 'гостиница', hu: 'szálloda', level: 'A2', pos: 'főnév', ex: 'Дорогая гостиница.', exHu: 'Drága szálloda.' },
  { ru: 'дорога', hu: 'út', level: 'A1', pos: 'főnév', ex: 'Длинная дорога.', exHu: 'Hosszú út.' },
  { ru: 'аэропорт', hu: 'repülőtér', level: 'A2', pos: 'főnév', ex: 'Международный аэропорт.', exHu: 'Nemzetközi repülőtér.' },
  { ru: 'граница', hu: 'határ', level: 'B1', pos: 'főnév', ex: 'Пересечь границу.', exHu: 'Átlépni a határt.' },
  // -- Természet --
  { ru: 'дерево', hu: 'fa', level: 'A1', pos: 'főnév', ex: 'Высокое дерево.', exHu: 'Magas fa.' },
  { ru: 'цветок', hu: 'virág', level: 'A1', pos: 'főnév', ex: 'Красивый цветок.', exHu: 'Szép virág.' },
  { ru: 'трава', hu: 'fű', level: 'A2', pos: 'főnév', ex: 'Зелёная трава.', exHu: 'Zöld fű.' },
  { ru: 'лес', hu: 'erdő', level: 'A1', pos: 'főnév', ex: 'Тёмный лес.', exHu: 'Sötét erdő.' },
  { ru: 'река', hu: 'folyó', level: 'A1', pos: 'főnév', ex: 'Широкая река.', exHu: 'Széles folyó.' },
  { ru: 'озеро', hu: 'tó', level: 'A2', pos: 'főnév', ex: 'Чистое озеро.', exHu: 'Tiszta tó.' },
  { ru: 'гора', hu: 'hegy', level: 'A1', pos: 'főnév', ex: 'Высокая гора.', exHu: 'Magas hegy.' },
  { ru: 'поле', hu: 'mező', level: 'A2', pos: 'főnév', ex: 'Зелёное поле.', exHu: 'Zöld mező.' },
  { ru: 'небо', hu: 'ég', level: 'A1', pos: 'főnév', ex: 'Ясное небо.', exHu: 'Tiszta ég.' },
  { ru: 'звезда', hu: 'csillag', level: 'A1', pos: 'főnév', ex: 'Яркая звезда.', exHu: 'Fényes csillag.' },
  { ru: 'солнце', hu: 'nap (égitest)', level: 'A1', pos: 'főnév', ex: 'Яркое солнце.', exHu: 'Ragyogó nap.' },
  { ru: 'луна', hu: 'hold', level: 'A1', pos: 'főnév', ex: 'Полная луна.', exHu: 'Telihold.' },
  { ru: 'камень', hu: 'kő', level: 'A2', pos: 'főnév', ex: 'Тяжёлый камень.', exHu: 'Nehéz kő.' },
  { ru: 'земля', hu: 'föld', level: 'A1', pos: 'főnév', ex: 'Мокрая земля.', exHu: 'Nedves föld.' },
  // -- Időjárás --
  { ru: 'дождь', hu: 'eső', level: 'A1', pos: 'főnév', ex: 'Идёт дождь.', exHu: 'Esik az eső.' },
  { ru: 'снег', hu: 'hó', level: 'A1', pos: 'főnév', ex: 'Белый снег.', exHu: 'Fehér hó.' },
  { ru: 'ветер', hu: 'szél', level: 'A1', pos: 'főnév', ex: 'Сильный ветер.', exHu: 'Erős szél.' },
  { ru: 'облако', hu: 'felhő', level: 'A2', pos: 'főnév', ex: 'Белое облако.', exHu: 'Fehér felhő.' },
  { ru: 'гроза', hu: 'zivatar', level: 'B1', pos: 'főnév', ex: 'Сильная гроза.', exHu: 'Erős zivatar.' },
  { ru: 'жара', hu: 'hőség', level: 'B1', pos: 'főnév', ex: 'Летняя жара.', exHu: 'Nyári hőség.' },
  { ru: 'мороз', hu: 'fagy', level: 'B1', pos: 'főnév', ex: 'Сильный мороз.', exHu: 'Erős fagy.' },
  { ru: 'туман', hu: 'köd', level: 'B1', pos: 'főnév', ex: 'Густой туман.', exHu: 'Sűrű köd.' },
  { ru: 'радуга', hu: 'szivárvány', level: 'B1', pos: 'főnév', ex: 'Яркая радуга.', exHu: 'Élénk szivárvány.' },
  { ru: 'молния', hu: 'villám', level: 'B2', pos: 'főnév', ex: 'Яркая молния.', exHu: 'Fényes villám.' },
  // -- Idő / naptár --
  { ru: 'час', hu: 'óra (időtartam)', level: 'A1', pos: 'főnév', ex: 'Через час.', exHu: 'Egy óra múlva.' },
  { ru: 'минута', hu: 'perc', level: 'A1', pos: 'főnév', ex: 'Пять минут.', exHu: 'Öt perc.' },
  { ru: 'неделя', hu: 'hét', level: 'A1', pos: 'főnév', ex: 'На этой неделе.', exHu: 'Ezen a héten.' },
  { ru: 'месяц', hu: 'hónap', level: 'A1', pos: 'főnév', ex: 'Через месяц.', exHu: 'Egy hónap múlva.' },
  { ru: 'вчера', hu: 'tegnap', level: 'A1', pos: 'határozószó', ex: 'Вчера был дождь.', exHu: 'Tegnap esett.' },
  { ru: 'понедельник', hu: 'hétfő', level: 'A1', pos: 'főnév', ex: 'В понедельник работаю.', exHu: 'Hétfőn dolgozom.' },
  { ru: 'вторник', hu: 'kedd', level: 'A1', pos: 'főnév', ex: 'Встреча во вторник.', exHu: 'Kedden találkozó.' },
  { ru: 'среда', hu: 'szerda', level: 'A1', pos: 'főnév', ex: 'Среда — середина недели.', exHu: 'A szerda a hét közepe.' },
  { ru: 'четверг', hu: 'csütörtök', level: 'A1', pos: 'főnév', ex: 'В четверг вечером.', exHu: 'Csütörtök este.' },
  { ru: 'пятница', hu: 'péntek', level: 'A1', pos: 'főnév', ex: 'Наконец пятница!', exHu: 'Végre péntek!' },
  { ru: 'суббота', hu: 'szombat', level: 'A1', pos: 'főnév', ex: 'В субботу отдыхаю.', exHu: 'Szombaton pihenek.' },
  { ru: 'воскресенье', hu: 'vasárnap', level: 'A1', pos: 'főnév', ex: 'Воскресенье — выходной.', exHu: 'A vasárnap szabadnap.' },
  { ru: 'весна', hu: 'tavasz', level: 'A2', pos: 'főnév', ex: 'Тёплая весна.', exHu: 'Meleg tavasz.' },
  { ru: 'осень', hu: 'ősz', level: 'A2', pos: 'főnév', ex: 'Золотая осень.', exHu: 'Aranyló ősz.' },
  // -- Számok --
  { ru: 'четыре', hu: 'négy', level: 'A1', pos: 'számnév', ex: 'Четыре стула.', exHu: 'Négy szék.' },
  { ru: 'пять', hu: 'öt', level: 'A1', pos: 'számnév', ex: 'Пять минут.', exHu: 'Öt perc.' },
  { ru: 'шесть', hu: 'hat', level: 'A1', pos: 'számnév', ex: 'Шесть часов.', exHu: 'Hat óra.' },
  { ru: 'семь', hu: 'hét', level: 'A1', pos: 'számnév', ex: 'Семь дней.', exHu: 'Hét nap.' },
  { ru: 'восемь', hu: 'nyolc', level: 'A1', pos: 'számnév', ex: 'Восемь часов.', exHu: 'Nyolc óra.' },
  { ru: 'девять', hu: 'kilenc', level: 'A1', pos: 'számnév', ex: 'Девять лет.', exHu: 'Kilenc év.' },
  { ru: 'десять', hu: 'tíz', level: 'A1', pos: 'számnév', ex: 'Десять рублей.', exHu: 'Tíz rubel.' },
  { ru: 'сто', hu: 'száz', level: 'A2', pos: 'számnév', ex: 'Сто лет.', exHu: 'Száz év.' },
  { ru: 'тысяча', hu: 'ezer', level: 'A2', pos: 'számnév', ex: 'Тысяча рублей.', exHu: 'Ezer rubel.' },
  { ru: 'первый', hu: 'első', level: 'A2', pos: 'sorszám', ex: 'Первый день.', exHu: 'Az első nap.' },
  { ru: 'второй', hu: 'második', level: 'A2', pos: 'sorszám', ex: 'Второй этаж.', exHu: 'Második emelet.' },
  // -- Érzések --
  { ru: 'радость', hu: 'öröm', level: 'A2', pos: 'főnév', ex: 'Большая радость.', exHu: 'Nagy öröm.' },
  { ru: 'счастье', hu: 'boldogság', level: 'A2', pos: 'főnév', ex: 'Полное счастье.', exHu: 'Teljes boldogság.' },
  { ru: 'страх', hu: 'félelem', level: 'B1', pos: 'főnév', ex: 'Сильный страх.', exHu: 'Erős félelem.' },
  { ru: 'любовь', hu: 'szerelem / szeretet', level: 'A2', pos: 'főnév', ex: 'Первая любовь.', exHu: 'Első szerelem.' },
  { ru: 'надежда', hu: 'remény', level: 'B1', pos: 'főnév', ex: 'Последняя надежда.', exHu: 'Az utolsó remény.' },
  { ru: 'гордость', hu: 'büszkeség', level: 'B1', pos: 'főnév', ex: 'Чувство гордости.', exHu: 'A büszkeség érzése.' },
  { ru: 'счастливый', hu: 'boldog', level: 'A2', pos: 'melléknév', ex: 'Счастливый день.', exHu: 'Boldog nap.' },
  { ru: 'грустный', hu: 'szomorú', level: 'A2', pos: 'melléknév', ex: 'Грустный фильм.', exHu: 'Szomorú film.' },
  { ru: 'злой', hu: 'dühös / gonosz', level: 'A2', pos: 'melléknév', ex: 'Злой человек.', exHu: 'Gonosz ember.' },
  { ru: 'весёлый', hu: 'vidám', level: 'A2', pos: 'melléknév', ex: 'Весёлый ребёнок.', exHu: 'Vidám gyerek.' },
  { ru: 'спокойный', hu: 'nyugodt', level: 'A2', pos: 'melléknév', ex: 'Спокойный вечер.', exHu: 'Nyugodt este.' },
  { ru: 'усталый', hu: 'fáradt', level: 'A2', pos: 'melléknév', ex: 'Усталый после работы.', exHu: 'Fáradt munka után.' },
  // -- Egészség --
  { ru: 'боль', hu: 'fájdalom', level: 'A2', pos: 'főnév', ex: 'Сильная боль.', exHu: 'Erős fájdalom.' },
  { ru: 'температура', hu: 'láz / hőmérséklet', level: 'A2', pos: 'főnév', ex: 'Высокая температура.', exHu: 'Magas láz.' },
  { ru: 'простуда', hu: 'megfázás', level: 'B1', pos: 'főnév', ex: 'Лёгкая простуда.', exHu: 'Enyhe megfázás.' },
  { ru: 'лекарство', hu: 'gyógyszer', level: 'A2', pos: 'főnév', ex: 'Принять лекарство.', exHu: 'Bevenni a gyógyszert.' },
  { ru: 'таблетка', hu: 'tabletta', level: 'B1', pos: 'főnév', ex: 'Одна таблетка.', exHu: 'Egy tabletta.' },
  { ru: 'здоровый', hu: 'egészséges', level: 'A2', pos: 'melléknév', ex: 'Здоровый образ жизни.', exHu: 'Egészséges életmód.' },
  { ru: 'больной', hu: 'beteg', level: 'A2', pos: 'melléknév', ex: 'Больной ребёнок.', exHu: 'Beteg gyerek.' },
  // -- Sport --
  { ru: 'спорт', hu: 'sport', level: 'A1', pos: 'főnév', ex: 'Люблю спорт.', exHu: 'Szeretem a sportot.' },
  { ru: 'футбол', hu: 'labdarúgás', level: 'A1', pos: 'főnév', ex: 'Играть в футбол.', exHu: 'Focizni.' },
  { ru: 'мяч', hu: 'labda', level: 'A1', pos: 'főnév', ex: 'Красный мяч.', exHu: 'Piros labda.' },
  { ru: 'команда', hu: 'csapat', level: 'A2', pos: 'főnév', ex: 'Наша команда.', exHu: 'A csapatunk.' },
  { ru: 'игра', hu: 'játék / meccs', level: 'A1', pos: 'főnév', ex: 'Интересная игра.', exHu: 'Érdekes meccs.' },
  { ru: 'победа', hu: 'győzelem', level: 'B1', pos: 'főnév', ex: 'Важная победа.', exHu: 'Fontos győzelem.' },
  { ru: 'плавание', hu: 'úszás', level: 'B1', pos: 'főnév', ex: 'Занятие по плаванию.', exHu: 'Úszásóra.' },
  { ru: 'бег', hu: 'futás', level: 'A2', pos: 'főnév', ex: 'Утренний бег.', exHu: 'Reggeli futás.' },
  { ru: 'стадион', hu: 'stadion', level: 'A2', pos: 'főnév', ex: 'Большой стадион.', exHu: 'Nagy stadion.' },
  // -- Zene --
  { ru: 'музыка', hu: 'zene', level: 'A1', pos: 'főnév', ex: 'Слушать музыку.', exHu: 'Zenét hallgatni.' },
  { ru: 'песня', hu: 'dal', level: 'A1', pos: 'főnév', ex: 'Красивая песня.', exHu: 'Szép dal.' },
  { ru: 'гитара', hu: 'gitár', level: 'A2', pos: 'főnév', ex: 'Играть на гитаре.', exHu: 'Gitározni.' },
  { ru: 'пианино', hu: 'zongora', level: 'A2', pos: 'főnév', ex: 'Играть на пианино.', exHu: 'Zongorázni.' },
  { ru: 'скрипка', hu: 'hegedű', level: 'B1', pos: 'főnév', ex: 'Звук скрипки.', exHu: 'A hegedű hangja.' },
  { ru: 'певец', hu: 'énekes', level: 'A2', pos: 'főnév', ex: 'Известный певец.', exHu: 'Híres énekes.' },
  { ru: 'концерт', hu: 'koncert', level: 'A2', pos: 'főnév', ex: 'Живой концерт.', exHu: 'Élő koncert.' },
  { ru: 'звук', hu: 'hang', level: 'A2', pos: 'főnév', ex: 'Громкий звук.', exHu: 'Hangos zaj.' },
  // -- Technológia --
  { ru: 'компьютер', hu: 'számítógép', level: 'A1', pos: 'főnév', ex: 'Новый компьютер.', exHu: 'Új számítógép.' },
  { ru: 'телефон', hu: 'telefon', level: 'A1', pos: 'főnév', ex: 'Мобильный телефон.', exHu: 'Mobiltelefon.' },
  { ru: 'экран', hu: 'képernyő', level: 'A2', pos: 'főnév', ex: 'Большой экран.', exHu: 'Nagy képernyő.' },
  { ru: 'интернет', hu: 'internet', level: 'A1', pos: 'főnév', ex: 'Быстрый интернет.', exHu: 'Gyors internet.' },
  { ru: 'сайт', hu: 'weboldal', level: 'A2', pos: 'főnév', ex: 'Полезный сайт.', exHu: 'Hasznos weboldal.' },
  { ru: 'программа', hu: 'program', level: 'A2', pos: 'főnév', ex: 'Новая программа.', exHu: 'Új program.' },
  { ru: 'пароль', hu: 'jelszó', level: 'A2', pos: 'főnév', ex: 'Забыть пароль.', exHu: 'Elfelejteni a jelszót.' },
  { ru: 'кнопка', hu: 'gomb', level: 'A2', pos: 'főnév', ex: 'Нажать кнопку.', exHu: 'Megnyomni a gombot.' },
  // -- Étterem / vásárlás --
  { ru: 'меню', hu: 'étlap', level: 'A2', pos: 'főnév', ex: 'Дайте меню.', exHu: 'Kérem az étlapot.' },
  { ru: 'счёт', hu: 'számla', level: 'A2', pos: 'főnév', ex: 'Принесите счёт.', exHu: 'Hozza a számlát.' },
  { ru: 'блюдо', hu: 'fogás / étel', level: 'B1', pos: 'főnév', ex: 'Вкусное блюдо.', exHu: 'Finom fogás.' },
  { ru: 'десерт', hu: 'desszert', level: 'A2', pos: 'főnév', ex: 'Сладкий десерт.', exHu: 'Édes desszert.' },
  { ru: 'ложка', hu: 'kanál', level: 'A2', pos: 'főnév', ex: 'Чайная ложка.', exHu: 'Kávéskanál.' },
  { ru: 'вилка', hu: 'villa', level: 'A2', pos: 'főnév', ex: 'Вилка и нож.', exHu: 'Villa és kés.' },
  { ru: 'нож', hu: 'kés', level: 'A2', pos: 'főnév', ex: 'Острый нож.', exHu: 'Éles kés.' },
  { ru: 'тарелка', hu: 'tányér', level: 'A2', pos: 'főnév', ex: 'Чистая тарелка.', exHu: 'Tiszta tányér.' },
  { ru: 'стакан', hu: 'pohár', level: 'A1', pos: 'főnév', ex: 'Стакан воды.', exHu: 'Egy pohár víz.' },
  { ru: 'чашка', hu: 'csésze', level: 'A1', pos: 'főnév', ex: 'Чашка кофе.', exHu: 'Egy csésze kávé.' },
  { ru: 'цена', hu: 'ár', level: 'A2', pos: 'főnév', ex: 'Высокая цена.', exHu: 'Magas ár.' },
  { ru: 'скидка', hu: 'kedvezmény', level: 'B1', pos: 'főnév', ex: 'Большая скидка.', exHu: 'Nagy kedvezmény.' },
  { ru: 'касса', hu: 'pénztár', level: 'A2', pos: 'főnév', ex: 'Оплатить на кассе.', exHu: 'Fizetni a pénztárnál.' },
  { ru: 'кошелёк', hu: 'pénztárca', level: 'B1', pos: 'főnév', ex: 'Кожаный кошелёк.', exHu: 'Bőr pénztárca.' },
  // -- Anyagok / szerszámok --
  { ru: 'металл', hu: 'fém', level: 'A2', pos: 'főnév', ex: 'Тяжёлый металл.', exHu: 'Nehéz fém.' },
  { ru: 'золото', hu: 'arany', level: 'A2', pos: 'főnév', ex: 'Чистое золото.', exHu: 'Tiszta arany.' },
  { ru: 'стекло', hu: 'üveg', level: 'A2', pos: 'főnév', ex: 'Разбитое стекло.', exHu: 'Törött üveg.' },
  { ru: 'бумага', hu: 'papír', level: 'A1', pos: 'főnév', ex: 'Лист бумаги.', exHu: 'Egy lap papír.' },
  { ru: 'ткань', hu: 'szövet', level: 'B1', pos: 'főnév', ex: 'Мягкая ткань.', exHu: 'Puha szövet.' },
  { ru: 'молоток', hu: 'kalapács', level: 'B1', pos: 'főnév', ex: 'Тяжёлый молоток.', exHu: 'Nehéz kalapács.' },
  { ru: 'ножницы', hu: 'olló', level: 'A2', pos: 'főnév', ex: 'Острые ножницы.', exHu: 'Éles olló.' },
  { ru: 'верёвка', hu: 'kötél', level: 'A2', pos: 'főnév', ex: 'Крепкая верёвка.', exHu: 'Erős kötél.' },
  // -- Földrajz --
  { ru: 'страна', hu: 'ország', level: 'A1', pos: 'főnév', ex: 'Большая страна.', exHu: 'Nagy ország.' },
  { ru: 'мир', hu: 'világ / béke', level: 'A1', pos: 'főnév', ex: 'Весь мир.', exHu: 'Az egész világ.' },
  { ru: 'столица', hu: 'főváros', level: 'A2', pos: 'főnév', ex: 'Столица России.', exHu: 'Oroszország fővárosa.' },
  { ru: 'океан', hu: 'óceán', level: 'A2', pos: 'főnév', ex: 'Тихий океан.', exHu: 'A Csendes-óceán.' },
  { ru: 'пустыня', hu: 'sivatag', level: 'B1', pos: 'főnév', ex: 'Жаркая пустыня.', exHu: 'Forró sivatag.' },
  { ru: 'север', hu: 'észak', level: 'A2', pos: 'főnév', ex: 'На севере холодно.', exHu: 'Északon hideg van.' },
  { ru: 'юг', hu: 'dél', level: 'A2', pos: 'főnév', ex: 'Ехать на юг.', exHu: 'Délre menni.' },
  { ru: 'восток', hu: 'kelet', level: 'A2', pos: 'főnév', ex: 'Солнце встаёт на востоке.', exHu: 'A nap keleten kel.' },
  { ru: 'запад', hu: 'nyugat', level: 'A2', pos: 'főnév', ex: 'Ветер с запада.', exHu: 'Nyugati szél.' },
  { ru: 'флаг', hu: 'zászló', level: 'A2', pos: 'főnév', ex: 'Государственный флаг.', exHu: 'Állami zászló.' },
  // -- Melléknevek (ellentétek) --
  { ru: 'сильный', hu: 'erős', level: 'A2', pos: 'melléknév', ex: 'Сильный человек.', exHu: 'Erős ember.' },
  { ru: 'слабый', hu: 'gyenge', level: 'A2', pos: 'melléknév', ex: 'Слабый ветер.', exHu: 'Gyenge szél.' },
  { ru: 'тёплый', hu: 'meleg', level: 'A2', pos: 'melléknév', ex: 'Тёплый день.', exHu: 'Meleg nap.' },
  { ru: 'холодный', hu: 'hideg', level: 'A1', pos: 'melléknév', ex: 'Холодная вода.', exHu: 'Hideg víz.' },
  { ru: 'чистый', hu: 'tiszta', level: 'A2', pos: 'melléknév', ex: 'Чистая комната.', exHu: 'Tiszta szoba.' },
  { ru: 'грязный', hu: 'piszkos', level: 'A2', pos: 'melléknév', ex: 'Грязные руки.', exHu: 'Piszkos kezek.' },
  { ru: 'полный', hu: 'tele / teljes', level: 'A2', pos: 'melléknév', ex: 'Полный стакан.', exHu: 'Tele pohár.' },
  { ru: 'пустой', hu: 'üres', level: 'A2', pos: 'melléknév', ex: 'Пустая комната.', exHu: 'Üres szoba.' },
  { ru: 'высокий', hu: 'magas', level: 'A1', pos: 'melléknév', ex: 'Высокий дом.', exHu: 'Magas ház.' },
  { ru: 'низкий', hu: 'alacsony', level: 'A2', pos: 'melléknév', ex: 'Низкий стол.', exHu: 'Alacsony asztal.' },
  { ru: 'длинный', hu: 'hosszú', level: 'A2', pos: 'melléknév', ex: 'Длинный день.', exHu: 'Hosszú nap.' },
  { ru: 'короткий', hu: 'rövid', level: 'A2', pos: 'melléknév', ex: 'Короткий путь.', exHu: 'Rövid út.' },
  { ru: 'широкий', hu: 'széles', level: 'B1', pos: 'melléknév', ex: 'Широкая улица.', exHu: 'Széles utca.' },
  { ru: 'узкий', hu: 'keskeny', level: 'B1', pos: 'melléknév', ex: 'Узкая тропа.', exHu: 'Keskeny ösvény.' },
  { ru: 'глубокий', hu: 'mély', level: 'B1', pos: 'melléknév', ex: 'Глубокое озеро.', exHu: 'Mély tó.' },
  { ru: 'тёмный', hu: 'sötét', level: 'A2', pos: 'melléknév', ex: 'Тёмная ночь.', exHu: 'Sötét éjszaka.' },
  { ru: 'светлый', hu: 'világos', level: 'A2', pos: 'melléknév', ex: 'Светлая комната.', exHu: 'Világos szoba.' },
  // -- Irányok --
  { ru: 'налево', hu: 'balra', level: 'A2', pos: 'határozószó', ex: 'Поверни налево.', exHu: 'Fordulj balra.' },
  { ru: 'направо', hu: 'jobbra', level: 'A2', pos: 'határozószó', ex: 'Иди направо.', exHu: 'Menj jobbra.' },
  { ru: 'прямо', hu: 'egyenesen', level: 'A2', pos: 'határozószó', ex: 'Иди прямо.', exHu: 'Menj egyenesen.' },
  { ru: 'близко', hu: 'közel', level: 'A2', pos: 'határozószó', ex: 'Магазин близко.', exHu: 'A bolt közel van.' },
  { ru: 'далеко', hu: 'messze', level: 'A2', pos: 'határozószó', ex: 'Дом далеко.', exHu: 'A ház messze van.' },
  { ru: 'внутри', hu: 'belül', level: 'B1', pos: 'határozószó', ex: 'Внутри тепло.', exHu: 'Belül meleg van.' },
  { ru: 'снаружи', hu: 'kívül', level: 'B2', pos: 'határozószó', ex: 'Снаружи холодно.', exHu: 'Kívül hideg van.' },
  // -- Igék (több) --
  { ru: 'делать', hu: 'csinálni', level: 'A1', pos: 'ige', ex: 'Что ты делаешь?', exHu: 'Mit csinálsz?' },
  { ru: 'думать', hu: 'gondolkodni', level: 'A1', pos: 'ige', ex: 'Я думаю о тебе.', exHu: 'Rád gondolok.' },
  { ru: 'спать', hu: 'aludni', level: 'A1', pos: 'ige', ex: 'Я хочу спать.', exHu: 'Aludni szeretnék.' },
  { ru: 'играть', hu: 'játszani', level: 'A1', pos: 'ige', ex: 'Дети играют.', exHu: 'A gyerekek játszanak.' },
  { ru: 'петь', hu: 'énekelni', level: 'A2', pos: 'ige', ex: 'Она поёт песню.', exHu: 'Dalt énekel.' },
  { ru: 'бежать', hu: 'futni', level: 'A2', pos: 'ige', ex: 'Я бегу домой.', exHu: 'Futok haza.' },
  { ru: 'ехать', hu: 'menni (járművel)', level: 'A1', pos: 'ige', ex: 'Я еду на работу.', exHu: 'Munkába megyek.' },
  { ru: 'смотреть', hu: 'nézni', level: 'A1', pos: 'ige', ex: 'Смотреть фильм.', exHu: 'Filmet nézni.' },
  { ru: 'слушать', hu: 'hallgatni', level: 'A1', pos: 'ige', ex: 'Слушать музыку.', exHu: 'Zenét hallgatni.' },
  { ru: 'встречать', hu: 'találkozni', level: 'A2', pos: 'ige', ex: 'Встречать друзей.', exHu: 'Barátokkal találkozni.' },
  { ru: 'звонить', hu: 'telefonálni', level: 'A2', pos: 'ige', ex: 'Звонить маме.', exHu: 'Anyát felhívni.' },
  { ru: 'платить', hu: 'fizetni', level: 'A2', pos: 'ige', ex: 'Платить картой.', exHu: 'Kártyával fizetni.' },
  { ru: 'готовить', hu: 'főzni / készíteni', level: 'A2', pos: 'ige', ex: 'Готовить ужин.', exHu: 'Vacsorát főzni.' },
  { ru: 'путешествовать', hu: 'utazni', level: 'B1', pos: 'ige', ex: 'Путешествовать по миру.', exHu: 'Bejárni a világot.' },
  { ru: 'отдыхать', hu: 'pihenni', level: 'A2', pos: 'ige', ex: 'Отдыхать на море.', exHu: 'A tengernél pihenni.' },
  // -- Elöljárók / kötőszavak --
  { ru: 'в', hu: '-ban / -be', level: 'A1', pos: 'elöljárószó', ex: 'Я в доме.', exHu: 'A házban vagyok.' },
  { ru: 'на', hu: '-on / -ra', level: 'A1', pos: 'elöljárószó', ex: 'Книга на столе.', exHu: 'A könyv az asztalon van.' },
  { ru: 'под', hu: 'alatt', level: 'A2', pos: 'elöljárószó', ex: 'Кот под столом.', exHu: 'A macska az asztal alatt.' },
  { ru: 'над', hu: 'fölött', level: 'A2', pos: 'elöljárószó', ex: 'Лампа над столом.', exHu: 'A lámpa az asztal fölött.' },
  { ru: 'между', hu: 'között', level: 'B1', pos: 'elöljárószó', ex: 'Между нами.', exHu: 'Köztünk.' },
  { ru: 'без', hu: 'nélkül', level: 'A2', pos: 'elöljárószó', ex: 'Чай без сахара.', exHu: 'Tea cukor nélkül.' },
  { ru: 'для', hu: 'számára / -nak', level: 'A2', pos: 'elöljárószó', ex: 'Подарок для мамы.', exHu: 'Ajándék anyának.' },
  { ru: 'после', hu: 'után', level: 'A2', pos: 'elöljárószó', ex: 'После обеда.', exHu: 'Ebéd után.' },
  { ru: 'и', hu: 'és', level: 'A1', pos: 'kötőszó', ex: 'Хлеб и молоко.', exHu: 'Kenyér és tej.' },
  { ru: 'но', hu: 'de', level: 'A1', pos: 'kötőszó', ex: 'Дёшево, но плохо.', exHu: 'Olcsó, de rossz.' },
  { ru: 'или', hu: 'vagy', level: 'A1', pos: 'kötőszó', ex: 'Чай или кофе?', exHu: 'Tea vagy kávé?' },
  { ru: 'если', hu: 'ha', level: 'A2', pos: 'kötőszó', ex: 'Если будет время.', exHu: 'Ha lesz idő.' },
  { ru: 'чтобы', hu: 'azért, hogy', level: 'B1', pos: 'kötőszó', ex: 'Учусь, чтобы знать.', exHu: 'Tanulok, hogy tudjak.' },
  { ru: 'очень', hu: 'nagyon', level: 'A1', pos: 'határozószó', ex: 'Очень вкусно.', exHu: 'Nagyon finom.' },
  { ru: 'много', hu: 'sok', level: 'A1', pos: 'határozószó', ex: 'Много людей.', exHu: 'Sok ember.' },
  { ru: 'немного', hu: 'egy kicsit', level: 'A2', pos: 'határozószó', ex: 'Немного устал.', exHu: 'Kicsit fáradt vagyok.' },
  // -- Haladó (B2) --
  { ru: 'ценность', hu: 'érték', level: 'B2', pos: 'főnév', ex: 'Культурная ценность.', exHu: 'Kulturális érték.' },
  { ru: 'вывод', hu: 'következtetés', level: 'B2', pos: 'főnév', ex: 'Сделать вывод.', exHu: 'Következtetést levonni.' },
  { ru: 'доказательство', hu: 'bizonyíték', level: 'B2', pos: 'főnév', ex: 'Веское доказательство.', exHu: 'Nyomós bizonyíték.' },
  { ru: 'тенденция', hu: 'tendencia', level: 'B2', pos: 'főnév', ex: 'Общая тенденция.', exHu: 'Általános tendencia.' },
  { ru: 'фактор', hu: 'tényező', level: 'B2', pos: 'főnév', ex: 'Ключевой фактор.', exHu: 'Kulcstényező.' },
  { ru: 'аспект', hu: 'szempont', level: 'B2', pos: 'főnév', ex: 'Важный аспект.', exHu: 'Fontos szempont.' },
  { ru: 'контекст', hu: 'kontextus', level: 'B2', pos: 'főnév', ex: 'В этом контексте.', exHu: 'Ebben a kontextusban.' },
  { ru: 'концепция', hu: 'koncepció', level: 'B2', pos: 'főnév', ex: 'Новая концепция.', exHu: 'Új koncepció.' },
  { ru: 'механизм', hu: 'mechanizmus', level: 'B2', pos: 'főnév', ex: 'Сложный механизм.', exHu: 'Bonyolult mechanizmus.' },
  { ru: 'структура', hu: 'struktúra', level: 'B2', pos: 'főnév', ex: 'Чёткая структура.', exHu: 'Világos struktúra.' },
  { ru: 'компромисс', hu: 'kompromisszum', level: 'B2', pos: 'főnév', ex: 'Найти компромисс.', exHu: 'Kompromisszumot találni.' },
  { ru: 'стереотип', hu: 'sztereotípia', level: 'B2', pos: 'főnév', ex: 'Разрушить стереотип.', exHu: 'Ledönteni egy sztereotípiát.' },
  // -- Haladó (C1) --
  { ru: 'феномен', hu: 'jelenség', level: 'C1', pos: 'főnév', ex: 'Редкий феномен.', exHu: 'Ritka jelenség.' },
  { ru: 'гипотеза', hu: 'hipotézis', level: 'C1', pos: 'főnév', ex: 'Проверить гипотезу.', exHu: 'Ellenőrizni a hipotézist.' },
  { ru: 'парадокс', hu: 'paradoxon', level: 'C1', pos: 'főnév', ex: 'Известный парадокс.', exHu: 'Ismert paradoxon.' },
  { ru: 'мировоззрение', hu: 'világnézet', level: 'C1', pos: 'főnév', ex: 'Целостное мировоззрение.', exHu: 'Egységes világnézet.' },
  { ru: 'предпосылка', hu: 'előfeltétel', level: 'C1', pos: 'főnév', ex: 'Основная предпосылка.', exHu: 'Alapvető előfeltétel.' },
  { ru: 'интуиция', hu: 'intuíció', level: 'C1', pos: 'főnév', ex: 'Доверять интуиции.', exHu: 'Bízni az intuícióban.' },
  { ru: 'солидарность', hu: 'szolidaritás', level: 'C1', pos: 'főnév', ex: 'Проявить солидарность.', exHu: 'Szolidaritást vállalni.' },
  { ru: 'самосознание', hu: 'öntudat', level: 'C1', pos: 'főnév', ex: 'Развитое самосознание.', exHu: 'Fejlett öntudat.' },
  { ru: 'целостность', hu: 'egység / integritás', level: 'C1', pos: 'főnév', ex: 'Целостность системы.', exHu: 'A rendszer egysége.' },
  { ru: 'амбиция', hu: 'ambíció', level: 'B2', pos: 'főnév', ex: 'Большие амбиции.', exHu: 'Nagy ambíciók.' },
  // -- Haladó (C2) --
  { ru: 'снисходительность', hu: 'elnézés / leereszkedés', level: 'C2', pos: 'főnév', ex: 'Излишняя снисходительность.', exHu: 'Túlzott elnézés.' },
  { ru: 'целеустремлённость', hu: 'céltudatosság', level: 'C2', pos: 'főnév', ex: 'Редкая целеустремлённость.', exHu: 'Ritka céltudatosság.' },
  { ru: 'добросовестность', hu: 'lelkiismeretesség', level: 'C2', pos: 'főnév', ex: 'Полная добросовестность.', exHu: 'Teljes lelkiismeretesség.' },
  { ru: 'безупречность', hu: 'kifogástalanság', level: 'C2', pos: 'főnév', ex: 'Безупречность работы.', exHu: 'A munka kifogástalansága.' },
  { ru: 'невозмутимость', hu: 'rendíthetetlenség', level: 'C2', pos: 'főnév', ex: 'Полная невозмутимость.', exHu: 'Teljes rendíthetetlenség.' },
  { ru: 'проницательный', hu: 'éleslátó', level: 'C2', pos: 'melléknév', ex: 'Проницательный ум.', exHu: 'Éleslátó elme.' },
  { ru: 'самоотверженный', hu: 'önfeláldozó', level: 'C2', pos: 'melléknév', ex: 'Самоотверженный поступок.', exHu: 'Önfeláldozó tett.' },
  { ru: 'непоколебимый', hu: 'megingathatatlan', level: 'C2', pos: 'melléknév', ex: 'Непоколебимая вера.', exHu: 'Megingathatatlan hit.' },
  { ru: 'изощряться', hu: 'kifinomultan mesterkedni', level: 'C2', pos: 'ige', ex: 'Изощряться в остротах.', exHu: 'Élcelődésben mesterkedni.' },
];

// Word groups (topic / grammar), each referencing words from RU_WORDS by `ru`.
window.RU_GROUPS = [
  // ── Témák ──
  { id: 'greetings', cat: 'topic', icon: '👋', title: 'Üdvözlések', words: ['привет', 'пока', 'здравствуйте', 'спасибо', 'пожалуйста', 'извините', 'да', 'нет'] },
  { id: 'family', cat: 'topic', icon: '👪', title: 'Család', words: ['семья', 'ребёнок', 'жена', 'муж', 'мама', 'папа', 'друг', 'человек'] },
  { id: 'food', cat: 'topic', icon: '🍎', title: 'Étel', words: ['еда', 'ужин', 'хлеб', 'молоко', 'сыр', 'мясо', 'рыба', 'суп', 'рис', 'соль', 'сахар', 'масло', 'яйцо', 'курица', 'колбаса', 'мёд', 'торт', 'печенье', 'мороженое', 'орех', 'каша'] },
  { id: 'fruit', cat: 'topic', icon: '🍓', title: 'Gyümölcs', words: ['яблоко', 'банан', 'апельсин', 'груша', 'виноград', 'клубника', 'лимон', 'вишня', 'арбуз', 'персик', 'слива', 'малина'] },
  { id: 'vegetables', cat: 'topic', icon: '🥕', title: 'Zöldség', words: ['помидор', 'картофель', 'огурец', 'лук', 'морковь', 'капуста', 'чеснок', 'грибы', 'перец'] },
  { id: 'drinks', cat: 'topic', icon: '🥤', title: 'Italok', words: ['вода', 'чай', 'кофе', 'сок', 'пиво', 'вино', 'лимонад', 'квас', 'молоко'] },
  { id: 'animals', cat: 'topic', icon: '🐶', title: 'Állatok', words: ['кот', 'собака', 'лошадь', 'корова', 'свинья', 'медведь', 'волк', 'лиса', 'заяц', 'лев', 'тигр', 'слон', 'обезьяна', 'змея', 'лягушка', 'мышь'] },
  { id: 'birds', cat: 'topic', icon: '🐦', title: 'Madarak és rovarok', words: ['птица', 'орёл', 'сова', 'утка', 'попугай', 'муха', 'комар', 'пчела', 'бабочка', 'паук'] },
  { id: 'sea', cat: 'topic', icon: '🌊', title: 'A tenger', words: ['море', 'пляж', 'волна', 'песок', 'рыба', 'акула', 'кит', 'дельфин', 'остров', 'корабль', 'лодка'] },
  { id: 'colors', cat: 'topic', icon: '🎨', title: 'Színek', words: ['красный', 'синий', 'зелёный', 'жёлтый', 'чёрный', 'белый', 'серый', 'розовый', 'коричневый', 'фиолетовый', 'голубой', 'оранжевый'] },
  { id: 'body', cat: 'topic', icon: '🧍', title: 'A test', words: ['голова', 'рука', 'нога', 'глаз', 'ухо', 'нос', 'рот', 'зуб', 'волосы', 'лицо', 'сердце', 'спина', 'палец', 'кровь', 'кожа'] },
  { id: 'clothes', cat: 'topic', icon: '👕', title: 'Ruhák', words: ['одежда', 'рубашка', 'платье', 'брюки', 'юбка', 'куртка', 'пальто', 'шапка', 'обувь', 'носки', 'перчатки', 'сумка', 'очки'] },
  { id: 'house', cat: 'topic', icon: '🏠', title: 'Ház', words: ['дом', 'квартира', 'комната', 'кухня', 'стена', 'пол', 'крыша', 'кровать', 'диван', 'шкаф', 'зеркало', 'лампа', 'ключ', 'лестница', 'мебель', 'окно', 'дверь', 'стол'] },
  { id: 'bathroom', cat: 'topic', icon: '🛁', title: 'Fürdőszoba', words: ['душ', 'ванна', 'туалет', 'полотенце', 'мыло', 'зеркало'] },
  { id: 'city', cat: 'topic', icon: '🏙️', title: 'Város', words: ['город', 'улица', 'площадь', 'банк', 'больница', 'аптека', 'парк', 'рынок', 'вокзал', 'мост', 'здание', 'музей', 'театр', 'библиотека', 'церковь', 'магазин'] },
  { id: 'school', cat: 'topic', icon: '🎒', title: 'Iskola', words: ['школа', 'урок', 'учитель', 'ученик', 'класс', 'тетрадь', 'ручка', 'карандаш', 'книга', 'экзамен', 'оценка', 'университет', 'студент', 'словарь', 'ошибка'] },
  { id: 'work', cat: 'topic', icon: '💼', title: 'Munka', words: ['работа', 'офис', 'начальник', 'зарплата', 'компания', 'встреча', 'договор', 'деньги'] },
  { id: 'jobs', cat: 'topic', icon: '👷', title: 'Foglalkozások', words: ['врач', 'инженер', 'повар', 'официант', 'продавец', 'водитель', 'полицейский', 'художник', 'писатель', 'программист', 'юрист', 'учитель'] },
  { id: 'travel', cat: 'topic', icon: '✈️', title: 'Utazás', words: ['путешествие', 'поезд', 'самолёт', 'машина', 'автобус', 'метро', 'такси', 'велосипед', 'паспорт', 'чемодан', 'карта', 'гостиница', 'билет', 'аэропорт', 'граница', 'дорога'] },
  { id: 'transport', cat: 'topic', icon: '🚗', title: 'Közlekedés', words: ['машина', 'автобус', 'поезд', 'самолёт', 'метро', 'такси', 'велосипед', 'корабль', 'дорога'] },
  { id: 'nature', cat: 'topic', icon: '🌳', title: 'Természet', words: ['природа', 'дерево', 'цветок', 'трава', 'лес', 'река', 'озеро', 'гора', 'поле', 'небо', 'звезда', 'солнце', 'луна', 'камень', 'земля'] },
  { id: 'weather', cat: 'topic', icon: '⛅', title: 'Időjárás', words: ['погода', 'дождь', 'снег', 'ветер', 'облако', 'гроза', 'жара', 'мороз', 'туман', 'радуга', 'молния', 'зима', 'лето', 'весна', 'осень'] },
  { id: 'time', cat: 'topic', icon: '⏰', title: 'Idő', words: ['время', 'час', 'минута', 'день', 'неделя', 'месяц', 'год', 'сегодня', 'завтра', 'вчера', 'утро', 'вечер', 'ночь', 'сейчас', 'потом'] },
  { id: 'calendar', cat: 'topic', icon: '📅', title: 'Napok és évszakok', words: ['понедельник', 'вторник', 'среда', 'четверг', 'пятница', 'суббота', 'воскресенье', 'весна', 'лето', 'осень', 'зима'] },
  { id: 'numbers', cat: 'topic', icon: '🔢', title: 'Számok', words: ['один', 'два', 'три', 'четыре', 'пять', 'шесть', 'семь', 'восемь', 'девять', 'десять', 'сто', 'тысяча', 'первый', 'второй'] },
  { id: 'emotions', cat: 'topic', icon: '😊', title: 'Érzések', words: ['радость', 'счастье', 'страх', 'любовь', 'надежда', 'гордость', 'счастливый', 'грустный', 'злой', 'весёлый', 'спокойный', 'усталый'] },
  { id: 'health', cat: 'topic', icon: '🩺', title: 'Egészség', words: ['здоровье', 'болезнь', 'боль', 'температура', 'простуда', 'лекарство', 'таблетка', 'здоровый', 'больной', 'врач', 'больница', 'аптека'] },
  { id: 'sports', cat: 'topic', icon: '⚽', title: 'Sport', words: ['спорт', 'футбол', 'мяч', 'команда', 'игра', 'победа', 'плавание', 'бег', 'стадион'] },
  { id: 'music', cat: 'topic', icon: '🎵', title: 'Zene', words: ['музыка', 'песня', 'гитара', 'пианино', 'скрипка', 'певец', 'концерт', 'звук'] },
  { id: 'technology', cat: 'topic', icon: '💻', title: 'Technológia', words: ['компьютер', 'телефон', 'экран', 'интернет', 'сайт', 'программа', 'пароль', 'кнопка'] },
  { id: 'restaurant', cat: 'topic', icon: '🍽️', title: 'Étterem', words: ['меню', 'счёт', 'блюдо', 'десерт', 'ложка', 'вилка', 'нож', 'тарелка', 'стакан', 'чашка', 'официант', 'еда'] },
  { id: 'shopping', cat: 'topic', icon: '🛒', title: 'Vásárlás', words: ['магазин', 'цена', 'деньги', 'скидка', 'касса', 'кошелёк', 'продавец', 'сумка'] },
  { id: 'materials', cat: 'topic', icon: '🧱', title: 'Anyagok', words: ['металл', 'золото', 'стекло', 'бумага', 'ткань', 'дерево', 'камень', 'молоток', 'ножницы', 'верёвка'] },
  { id: 'geography', cat: 'topic', icon: '🗺️', title: 'Földrajz', words: ['страна', 'мир', 'столица', 'океан', 'пустыня', 'север', 'юг', 'восток', 'запад', 'флаг', 'карта', 'граница'] },
  { id: 'opposites', cat: 'topic', icon: '↔️', title: 'Ellentétek', words: ['большой', 'маленький', 'сильный', 'слабый', 'тёплый', 'холодный', 'чистый', 'грязный', 'полный', 'пустой', 'высокий', 'низкий', 'длинный', 'короткий', 'тёмный', 'светлый', 'новый', 'старый'] },

  // ── Nyelvtan ──
  { id: 'pronouns', cat: 'grammar', icon: '🧑', title: 'Névmások', words: ['я', 'ты', 'он', 'она', 'мы', 'вы', 'они', 'это'] },
  { id: 'questions', cat: 'grammar', icon: '❓', title: 'Kérdőszavak', words: ['кто', 'что', 'где', 'когда', 'как', 'почему'] },
  { id: 'verbs_basic', cat: 'grammar', icon: '🅰️', title: 'Alap igék', words: ['быть', 'жить', 'знать', 'говорить', 'читать', 'писать', 'любить', 'хотеть', 'идти', 'есть', 'пить', 'делать', 'думать', 'спать', 'играть', 'петь', 'ехать', 'смотреть', 'слушать', 'готовить', 'отдыхать', 'работать'] },
  { id: 'adjectives', cat: 'grammar', icon: '✨', title: 'Melléknevek', words: ['большой', 'маленький', 'новый', 'старый', 'хороший', 'красивый', 'трудный', 'лёгкий', 'быстрый', 'медленный', 'важный', 'интересный', 'дорогой', 'дешёвый', 'сильный', 'слабый'] },
  { id: 'prepositions', cat: 'grammar', icon: '🔗', title: 'Elöljárók', words: ['в', 'на', 'под', 'над', 'между', 'без', 'для', 'после'] },
  { id: 'conjunctions', cat: 'grammar', icon: '🧩', title: 'Kötőszavak', words: ['и', 'но', 'или', 'если', 'чтобы', 'хотя', 'поэтому'] },
  { id: 'adverbs', cat: 'grammar', icon: '🔁', title: 'Határozószavak', words: ['очень', 'много', 'немного', 'всегда', 'никогда', 'часто', 'редко', 'здесь', 'там', 'сейчас', 'потом'] },
  { id: 'directions', cat: 'grammar', icon: '🧭', title: 'Irányok', words: ['налево', 'направо', 'прямо', 'близко', 'далеко', 'внутри', 'снаружи', 'здесь', 'там'] },
];
